//! BB #22a — Materializer Composer.
//!
//! Concatenates per-broker materializer segment files in operator-declared
//! order into `current-projection.md`. **Governance segment ALWAYS first**
//! regardless of operator order (R-O-3 closure, Untunable per Phase 9.1).
//!
//! ## Per-segment ordering (Wave 3)
//!
//! Three classes of segments:
//! 1. **Governance** — placed FIRST (R-O-3 closure; Untunable).
//! 2. **Operator-ordered non-governance** — appended in the order declared
//!    in cluster manifest `materializer.composition_order`.
//! 3. **Unordered remainder** — any segment files in the segments_dir not
//!    listed in composition_order are appended at the end alphabetically
//!    (so new brokers added without manifest updates still appear).
//!
//! ## Truncation behavior (R-O-3 closure)
//!
//! If composed total exceeds `context_budget_chars`, the composer emits a
//! `materializer_truncation_imminent` warning via `tracing::warn!` and falls
//! back to a governance-only projection with a marker
//! `[capability-segments-omitted-due-to-budget]`. BB #28 Diagnostics
//! (deferred) would replace the tracing call with a proper event.

pub mod awareness;
pub mod hot_store;

use std::collections::HashSet;
use std::path::PathBuf;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum MaterializerError {
    #[error("io error: {0}")]
    IoError(#[from] std::io::Error),

    #[error("composition budget exceeded; output truncated to governance-only")]
    BudgetExceeded { actual: usize, budget: usize },
}

pub struct MaterializerComposer {
    output_path: PathBuf,
    segments_dir: PathBuf,
    context_budget_chars: usize,
}

impl MaterializerComposer {
    pub fn new(output_path: PathBuf, segments_dir: PathBuf, context_budget_chars: usize) -> Self {
        Self {
            output_path,
            segments_dir,
            context_budget_chars,
        }
    }

    /// Compose all segments into `current-projection.md` per the governance-
    /// first override + operator-declared order + unordered remainder rules.
    pub fn compose(&self, operator_order: &[String]) -> Result<(), MaterializerError> {
        let mut body = String::new();
        body.push_str(
            "<!--\nThis file is generated by neurogrim-brokers' Materializer Composer.\n\
             Do not edit by hand; updates are produced on every broker tick.\n\
             Composition: governance segment first (Untunable per R-O-3 closure),\n\
             then operator-declared non-governance order, then unordered remainder.\n-->\n\n",
        );

        // (1) Governance segment FIRST — Untunable
        body.push_str("# Broker framework governance (always-reachable)\n\n");
        match self.read_segment("governance-pipelines") {
            Ok(content) => body.push_str(&content),
            Err(_) => body.push_str(
                "_No governance pipelines segment present (broker harness may be in early setup)._\n",
            ),
        }
        body.push_str("\n---\n\n");

        // (2) Operator-declared non-governance segments
        let mut emitted: HashSet<String> = HashSet::from(["governance-pipelines".to_string()]);
        body.push_str("# Broker overlays + awareness routing\n\n");
        for name in operator_order {
            if name == "governance-pipelines" {
                continue;
            }
            if let Ok(content) = self.read_segment(name) {
                body.push_str(&content);
                body.push_str("\n");
                emitted.insert(name.clone());
            }
        }

        // (3) Unordered remainder (alphabetical for determinism)
        let mut remaining: Vec<String> = self
            .list_segments()?
            .into_iter()
            .filter(|n| !emitted.contains(n))
            .collect();
        remaining.sort();
        for name in remaining {
            if let Ok(content) = self.read_segment(&name) {
                body.push_str(&content);
                body.push_str("\n");
            }
        }

        // Truncation check (R-O-3 closure)
        if body.len() > self.context_budget_chars {
            tracing::warn!(
                actual_chars = body.len(),
                budget_chars = self.context_budget_chars,
                "materializer_truncation_imminent: composition exceeds budget; falling back to governance-only"
            );
            let fallback = self.governance_only_fallback();
            self.write_output(&fallback)?;
            return Err(MaterializerError::BudgetExceeded {
                actual: body.len(),
                budget: self.context_budget_chars,
            });
        }

        self.write_output(&body)?;
        Ok(())
    }

    fn governance_only_fallback(&self) -> String {
        let mut body = String::new();
        body.push_str(
            "<!--\nGenerated by neurogrim-brokers Materializer Composer.\n\
             FALLBACK MODE: composition budget exceeded; only governance segment + \n\
             omission marker emitted (R-O-3 closure truncation-alarm behavior).\n-->\n\n",
        );
        body.push_str("# Broker framework governance (always-reachable)\n\n");
        match self.read_segment("governance-pipelines") {
            Ok(content) => body.push_str(&content),
            Err(_) => body.push_str("_No governance pipelines segment present._\n"),
        }
        body.push_str("\n[capability-segments-omitted-due-to-budget; see telemetry]\n");
        body
    }

    fn read_segment(&self, name: &str) -> Result<String, std::io::Error> {
        let path = self.segments_dir.join(format!("{}.md", name));
        std::fs::read_to_string(path)
    }

    fn list_segments(&self) -> Result<Vec<String>, std::io::Error> {
        let mut out = Vec::new();
        if !self.segments_dir.exists() {
            return Ok(out);
        }
        for entry in std::fs::read_dir(&self.segments_dir)? {
            let entry = entry?;
            if let Some(name) = entry.path().file_stem().and_then(|s| s.to_str()) {
                if entry.path().extension().and_then(|s| s.to_str()) == Some("md") {
                    out.push(name.to_string());
                }
            }
        }
        Ok(out)
    }

    fn write_output(&self, content: &str) -> Result<(), std::io::Error> {
        if let Some(parent) = self.output_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&self.output_path, content)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn setup_segments(tmp: &TempDir, segments: &[(&str, &str)]) -> (PathBuf, PathBuf) {
        let segments_dir = tmp.path().join("segments");
        std::fs::create_dir_all(&segments_dir).unwrap();
        for (name, content) in segments {
            std::fs::write(
                segments_dir.join(format!("{}.md", name)),
                content,
            )
            .unwrap();
        }
        let output_path = tmp.path().join("current-projection.md");
        (output_path, segments_dir)
    }

    #[test]
    fn composer_emits_governance_first() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-foo", "## Overlay FOO\n"),
                ("governance-pipelines", "## arm-kill-switch + check-trust-budget\n"),
                ("awareness-routing-foo", "## Awareness routing FOO\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        composer
            .compose(&[
                "overlay-foo".to_string(),
                "awareness-routing-foo".to_string(),
            ])
            .unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // Governance MUST appear before overlay/awareness
        let gov_pos = result.find("arm-kill-switch").unwrap();
        let overlay_pos = result.find("Overlay FOO").unwrap();
        let awareness_pos = result.find("Awareness routing FOO").unwrap();
        assert!(gov_pos < overlay_pos);
        assert!(gov_pos < awareness_pos);
    }

    #[test]
    fn composer_respects_operator_order_for_non_governance() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-a", "ALPHA OVERLAY\n"),
                ("overlay-b", "BETA OVERLAY\n"),
                ("governance-pipelines", "GOVERNANCE\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        composer
            .compose(&["overlay-b".to_string(), "overlay-a".to_string()])
            .unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // BETA must appear before ALPHA per operator order
        assert!(result.find("BETA OVERLAY").unwrap() < result.find("ALPHA OVERLAY").unwrap());
    }

    #[test]
    fn composer_appends_unordered_remainder() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-a", "ALPHA\n"),
                ("overlay-b", "BETA\n"),
                ("governance-pipelines", "GOV\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        // Operator only declared overlay-a; overlay-b should still appear at end
        composer.compose(&["overlay-a".to_string()]).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        assert!(result.contains("ALPHA"));
        assert!(result.contains("BETA"));
    }

    #[test]
    fn composer_falls_back_to_governance_only_when_budget_exceeded() {
        let tmp = TempDir::new().unwrap();
        let big_content = "x".repeat(50_000);
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-big", &big_content),
                ("governance-pipelines", "GOVERNANCE-MUST-SURVIVE\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 5_000);
        let err = composer.compose(&["overlay-big".to_string()]).unwrap_err();
        assert!(matches!(err, MaterializerError::BudgetExceeded { .. }));
        let result = std::fs::read_to_string(&output).unwrap();
        assert!(result.contains("GOVERNANCE-MUST-SURVIVE"));
        assert!(result.contains("[capability-segments-omitted-due-to-budget"));
        assert!(!result.contains(&"x".repeat(100)));
    }

    #[test]
    fn composer_handles_missing_governance_segment_gracefully() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(&tmp, &[("overlay-a", "ALPHA\n")]);
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        composer.compose(&["overlay-a".to_string()]).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // Falls back with a marker rather than failing
        assert!(result.contains("No governance pipelines segment"));
        assert!(result.contains("ALPHA"));
    }
}
