//! BB #22a — Materializer Composer.
//!
//! Concatenates per-broker materializer segment files in operator-declared
//! order into `current-projection.md`. **Governance segment ALWAYS first**
//! regardless of operator order (R-O-3 closure, Untunable per Phase 9.1).
//!
//! ## Per-segment ordering (Wave 3)
//!
//! Three classes of segments:
//! 1. **Governance** — placed FIRST (R-O-3 closure; Untunable).
//! 2. **Operator-ordered non-governance** — appended in the order declared
//!    in cluster manifest `materializer.composition_order`.
//! 3. **Unordered remainder** — any segment files in the segments_dir not
//!    listed in composition_order are appended at the end alphabetically
//!    (so new brokers added without manifest updates still appear).
//!
//! ## Truncation behavior (R-O-3 closure)
//!
//! If composed total exceeds `context_budget_chars`, the composer emits a
//! `materializer_truncation_imminent` warning via `tracing::warn!` and falls
//! back to a governance-only projection with a marker
//! `[capability-segments-omitted-due-to-budget]`. BB #28 Diagnostics
//! (deferred) would replace the tracing call with a proper event.

pub mod awareness;
pub mod cmdb_writer;
pub mod hot_store;

use std::collections::HashSet;
use std::path::PathBuf;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum MaterializerError {
    #[error("io error: {0}")]
    IoError(#[from] std::io::Error),

    #[error("composition budget exceeded; output truncated to governance-only")]
    BudgetExceeded { actual: usize, budget: usize },

    #[error("governance segment missing — strict mode required it (V0-RETROSPECTIVE §C4 closure)")]
    GovernanceSegmentMissing,
}

pub struct MaterializerComposer {
    output_path: PathBuf,
    segments_dir: PathBuf,
    context_budget_chars: usize,
    /// V0-RETROSPECTIVE §C4 closure (gap #12): when true, compose fails if
    /// the governance-pipelines segment file is missing. Production deployments
    /// MUST enable this; first-boot / dev sets false. The spec amendment in
    /// BB #22a documents the field; this is the field's runtime home.
    enforce_governance_segment_present: bool,
}

impl MaterializerComposer {
    /// Construct with strict mode disabled (V0 default — onboarding-friendly).
    pub fn new(output_path: PathBuf, segments_dir: PathBuf, context_budget_chars: usize) -> Self {
        Self {
            output_path,
            segments_dir,
            context_budget_chars,
            enforce_governance_segment_present: false,
        }
    }

    /// Production-mode constructor: strict-mode enabled per
    /// V0-RETROSPECTIVE §C4. Missing governance-pipelines segment fails
    /// compose with `MaterializerError::GovernanceSegmentMissing`.
    pub fn new_strict(
        output_path: PathBuf,
        segments_dir: PathBuf,
        context_budget_chars: usize,
    ) -> Self {
        Self {
            output_path,
            segments_dir,
            context_budget_chars,
            enforce_governance_segment_present: true,
        }
    }

    /// Toggle strict mode at runtime (for cluster-manifest-driven enforcement).
    pub fn set_strict(&mut self, strict: bool) {
        self.enforce_governance_segment_present = strict;
    }

    /// Compose all segments into `current-projection.md` per the governance-
    /// first override + operator-declared order + unordered remainder rules.
    ///
    /// **A10 — per-broker budget allocation (V0-RETRO ultra-pass A10):** at
    /// IDE scale (8–12 brokers, ~2-3KB each) the V0 16KB context budget
    /// gets blown; V0's behavior was a brutal governance-only fallback that
    /// lost every per-broker awareness segment. A10 changes this to:
    ///
    /// 1. Reserve `MIN_GOVERNANCE_RESERVE` chars for governance (always full).
    /// 2. Divide remaining budget across non-governance segments.
    /// 3. Each non-governance segment truncates to its allocation, appending
    ///    a `_[truncated: M chars; query broker for full schema]_` marker.
    /// 4. Fallback to governance-only only when budget can't even fit the
    ///    governance + overhead (extreme edge case).
    ///
    /// Preserves V0-RETRO §C1 (Composer is the primary agent-facing interface)
    /// + R-O-3 governance-first override (Untunable).
    pub fn compose(&self, operator_order: &[String]) -> Result<(), MaterializerError> {
        const MIN_GOVERNANCE_RESERVE: usize = 3072;
        // Boilerplate (header + section markers) — keep a small reserve so
        // segments don't blow the budget after framing.
        const FRAMING_OVERHEAD: usize = 512;

        let header = "<!--\nThis file is generated by neurogrim-brokers' Materializer Composer.\nDo not edit by hand; updates are produced on every broker tick.\nComposition: governance segment first (Untunable per R-O-3 closure),\nthen operator-declared non-governance order, then unordered remainder.\nA10: per-broker budget allocation when total composition would exceed budget.\n-->\n\n";

        // (1) Build the governance section (always full; never truncated).
        let mut governance_section = String::from(header);
        governance_section.push_str("# Broker framework governance (always-reachable)\n\n");
        match self.read_segment("governance-pipelines") {
            Ok(content) => governance_section.push_str(&content),
            Err(_) if self.enforce_governance_segment_present => {
                return Err(MaterializerError::GovernanceSegmentMissing);
            }
            Err(_) => governance_section.push_str(
                "_No governance pipelines segment present (broker harness may be in early setup; production should enable strict mode)._\n",
            ),
        }
        governance_section.push_str("\n---\n\n# Broker overlays + awareness routing\n\n");

        // (2) Enumerate non-governance segments in (operator-order + unordered-remainder) order.
        let mut emitted: HashSet<String> = HashSet::from(["governance-pipelines".to_string()]);
        let mut ordered_names: Vec<String> = Vec::new();
        for name in operator_order {
            if name == "governance-pipelines" {
                continue;
            }
            if !emitted.contains(name) && self.read_segment(name).is_ok() {
                ordered_names.push(name.clone());
                emitted.insert(name.clone());
            }
        }
        let mut remaining: Vec<String> = self
            .list_segments()?
            .into_iter()
            .filter(|n| !emitted.contains(n))
            .collect();
        remaining.sort();
        ordered_names.extend(remaining);

        // (3) Budget math: if governance alone exceeds the budget, hard-fall
        // back to governance-only. Otherwise compute per-segment allocation
        // for non-governance segments.
        if governance_section.len() + FRAMING_OVERHEAD > self.context_budget_chars {
            tracing::warn!(
                governance_chars = governance_section.len(),
                budget_chars = self.context_budget_chars,
                "materializer_truncation_imminent: governance segment alone exceeds budget; falling back to governance-only"
            );
            let fallback = self.governance_only_fallback();
            self.write_output(&fallback)?;
            return Err(MaterializerError::BudgetExceeded {
                actual: governance_section.len(),
                budget: self.context_budget_chars,
            });
        }
        let reserved = std::cmp::max(governance_section.len(), MIN_GOVERNANCE_RESERVE);
        let non_governance_budget = self
            .context_budget_chars
            .saturating_sub(reserved + FRAMING_OVERHEAD);
        let per_segment_budget = if ordered_names.is_empty() {
            0
        } else {
            non_governance_budget / ordered_names.len()
        };

        // (4) Assemble final body: governance first (full), then per-segment
        // truncated copies. Compute total used + bail to fallback if even
        // truncation can't keep us under budget.
        let mut body = governance_section;
        for name in &ordered_names {
            if let Ok(content) = self.read_segment(name) {
                let (rendered, was_truncated) =
                    truncate_segment(&content, per_segment_budget);
                body.push_str(&rendered);
                if was_truncated {
                    body.push_str("\n");
                } else {
                    body.push_str("\n");
                }
            }
        }

        // A10: with per-segment truncation, body should fit; only fall back
        // if something pathological happened (e.g., framing overhead miscalc).
        if body.len() > self.context_budget_chars {
            tracing::warn!(
                actual_chars = body.len(),
                budget_chars = self.context_budget_chars,
                "materializer_truncation_imminent: per-segment truncation insufficient; falling back to governance-only"
            );
            let fallback = self.governance_only_fallback();
            self.write_output(&fallback)?;
            return Err(MaterializerError::BudgetExceeded {
                actual: body.len(),
                budget: self.context_budget_chars,
            });
        }

        self.write_output(&body)?;
        Ok(())
    }

    fn governance_only_fallback(&self) -> String {
        let mut body = String::new();
        body.push_str(
            "<!--\nGenerated by neurogrim-brokers Materializer Composer.\n\
             FALLBACK MODE: composition budget exceeded; only governance segment + \n\
             omission marker emitted (R-O-3 closure truncation-alarm behavior).\n-->\n\n",
        );
        body.push_str("# Broker framework governance (always-reachable)\n\n");
        match self.read_segment("governance-pipelines") {
            Ok(content) => body.push_str(&content),
            Err(_) => body.push_str("_No governance pipelines segment present._\n"),
        }
        body.push_str("\n[capability-segments-omitted-due-to-budget; see telemetry]\n");
        body
    }

    fn read_segment(&self, name: &str) -> Result<String, std::io::Error> {
        let path = self.segments_dir.join(format!("{}.md", name));
        std::fs::read_to_string(path)
    }

    fn list_segments(&self) -> Result<Vec<String>, std::io::Error> {
        let mut out = Vec::new();
        if !self.segments_dir.exists() {
            return Ok(out);
        }
        for entry in std::fs::read_dir(&self.segments_dir)? {
            let entry = entry?;
            if let Some(name) = entry.path().file_stem().and_then(|s| s.to_str()) {
                if entry.path().extension().and_then(|s| s.to_str()) == Some("md") {
                    out.push(name.to_string());
                }
            }
        }
        Ok(out)
    }

    fn write_output(&self, content: &str) -> Result<(), std::io::Error> {
        if let Some(parent) = self.output_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&self.output_path, content)
    }
}

/// A10: truncate a per-broker segment to fit within `budget` chars, appending
/// a marker line indicating how much was dropped. The marker keeps the agent
/// aware that there's more content available via direct broker query, so the
/// truncation doesn't silently hide pipelines.
///
/// Budget of 0 means "no room at all" — emit only the marker so the agent
/// at least knows the broker exists. If `content` fits within `budget`, no
/// truncation; returns `(content, false)`.
fn truncate_segment(content: &str, budget: usize) -> (String, bool) {
    if budget == 0 {
        return (
            "_[broker segment omitted: per-broker context budget exhausted; query broker directly for awareness routing]_\n".to_string(),
            true,
        );
    }
    if content.len() <= budget {
        return (content.to_string(), false);
    }
    // Reserve ~120 chars for the truncation marker so the truncated content
    // + marker together don't exceed the budget.
    const MARKER_RESERVE: usize = 128;
    let take = budget.saturating_sub(MARKER_RESERVE);
    // Truncate at a UTF-8 char boundary.
    let mut end = take;
    while end > 0 && !content.is_char_boundary(end) {
        end -= 1;
    }
    let dropped = content.len() - end;
    let mut out = String::with_capacity(end + MARKER_RESERVE);
    out.push_str(&content[..end]);
    out.push_str(&format!(
        "\n\n_[truncated: {} more chars in this segment; query broker for full schema]_\n",
        dropped
    ));
    (out, true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn setup_segments(tmp: &TempDir, segments: &[(&str, &str)]) -> (PathBuf, PathBuf) {
        let segments_dir = tmp.path().join("segments");
        std::fs::create_dir_all(&segments_dir).unwrap();
        for (name, content) in segments {
            std::fs::write(
                segments_dir.join(format!("{}.md", name)),
                content,
            )
            .unwrap();
        }
        let output_path = tmp.path().join("current-projection.md");
        (output_path, segments_dir)
    }

    #[test]
    fn composer_emits_governance_first() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-foo", "## Overlay FOO\n"),
                ("governance-pipelines", "## arm-kill-switch + check-trust-budget\n"),
                ("awareness-routing-foo", "## Awareness routing FOO\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        composer
            .compose(&[
                "overlay-foo".to_string(),
                "awareness-routing-foo".to_string(),
            ])
            .unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // Governance MUST appear before overlay/awareness
        let gov_pos = result.find("arm-kill-switch").unwrap();
        let overlay_pos = result.find("Overlay FOO").unwrap();
        let awareness_pos = result.find("Awareness routing FOO").unwrap();
        assert!(gov_pos < overlay_pos);
        assert!(gov_pos < awareness_pos);
    }

    #[test]
    fn composer_respects_operator_order_for_non_governance() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-a", "ALPHA OVERLAY\n"),
                ("overlay-b", "BETA OVERLAY\n"),
                ("governance-pipelines", "GOVERNANCE\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        composer
            .compose(&["overlay-b".to_string(), "overlay-a".to_string()])
            .unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // BETA must appear before ALPHA per operator order
        assert!(result.find("BETA OVERLAY").unwrap() < result.find("ALPHA OVERLAY").unwrap());
    }

    #[test]
    fn composer_appends_unordered_remainder() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-a", "ALPHA\n"),
                ("overlay-b", "BETA\n"),
                ("governance-pipelines", "GOV\n"),
            ],
        );
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        // Operator only declared overlay-a; overlay-b should still appear at end
        composer.compose(&["overlay-a".to_string()]).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        assert!(result.contains("ALPHA"));
        assert!(result.contains("BETA"));
    }

    /// A10: a single oversized non-governance segment gets TRUNCATED with a
    /// marker, not dropped entirely. (V0 behavior was governance-only
    /// fallback; that was brutal at IDE scale.)
    #[test]
    fn composer_truncates_oversized_segment_with_marker() {
        let tmp = TempDir::new().unwrap();
        let big_content = "x".repeat(50_000);
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("overlay-big", &big_content),
                ("governance-pipelines", "GOVERNANCE-MUST-SURVIVE\n"),
            ],
        );
        // Budget = 5KB; governance reserve = 3KB; per-segment ~ 1.4KB
        let composer = MaterializerComposer::new(output.clone(), segments, 5_000);
        composer.compose(&["overlay-big".to_string()]).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // Governance always survives
        assert!(result.contains("GOVERNANCE-MUST-SURVIVE"));
        // Segment was truncated, not dropped — marker present
        assert!(
            result.contains("[truncated:"),
            "expected truncation marker, got: {}",
            result
        );
        // Truncated content STILL appears (just shorter than 50KB)
        assert!(result.contains("xxx"));
        // Total is within budget
        assert!(result.len() <= 5_000, "actual {} > budget 5_000", result.len());
    }

    /// A10: total goes over what the budget naturally fits → IDE scale case.
    /// 8 brokers each contributing 2KB; budget 16KB; governance gets 3KB,
    /// each broker gets ~1.5KB.
    #[test]
    fn composer_per_broker_budget_allocation_at_ide_scale() {
        let tmp = TempDir::new().unwrap();
        let segments = (0..8)
            .map(|i| (format!("overlay-{}", i), "y".repeat(2_000)))
            .collect::<Vec<_>>();
        let mut s: Vec<(&str, &str)> = segments
            .iter()
            .map(|(k, v)| (k.as_str(), v.as_str()))
            .collect();
        s.push(("governance-pipelines", "GOV"));
        let (output, segments_dir) = setup_segments(&tmp, &s);
        let composer = MaterializerComposer::new(output.clone(), segments_dir, 16_384);
        let order: Vec<String> = (0..8).map(|i| format!("overlay-{}", i)).collect();
        composer.compose(&order).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // Each broker's segment appears (perhaps truncated) — agent still
        // sees ALL brokers, not just governance.
        for i in 0..8 {
            assert!(
                result.contains(&format!("overlay-{}", i))
                    || result.contains("[truncated"),
                "broker {} missing entirely from projection",
                i
            );
        }
        assert!(result.contains("GOV"));
        assert!(result.len() <= 16_384);
    }

    #[test]
    fn composer_handles_missing_governance_segment_gracefully() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(&tmp, &[("overlay-a", "ALPHA\n")]);
        let composer = MaterializerComposer::new(output.clone(), segments, 100_000);
        composer.compose(&["overlay-a".to_string()]).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        // Falls back with a marker rather than failing
        assert!(result.contains("No governance pipelines segment"));
        assert!(result.contains("ALPHA"));
    }

    #[test]
    fn composer_strict_mode_rejects_missing_governance_segment() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(&tmp, &[("overlay-a", "ALPHA\n")]);
        let composer =
            MaterializerComposer::new_strict(output.clone(), segments, 100_000);
        let err = composer.compose(&["overlay-a".to_string()]).unwrap_err();
        assert!(matches!(err, MaterializerError::GovernanceSegmentMissing));
        // Output file should NOT be written when strict mode rejects
        assert!(!output.exists());
    }

    #[test]
    fn composer_strict_mode_succeeds_when_governance_present() {
        let tmp = TempDir::new().unwrap();
        let (output, segments) = setup_segments(
            &tmp,
            &[
                ("governance-pipelines", "GOV\n"),
                ("overlay-a", "ALPHA\n"),
            ],
        );
        let composer = MaterializerComposer::new_strict(output.clone(), segments, 100_000);
        composer.compose(&["overlay-a".to_string()]).unwrap();
        let result = std::fs::read_to_string(&output).unwrap();
        assert!(result.contains("GOV"));
        assert!(result.contains("ALPHA"));
    }
}
