//! Append-only event-log queue substrate (S13-B-1, v4.1).
//!
//! This is **Pattern 1** from S13's two-patterns-one-primitive split:
//! a fan-out, multi-consumer event log with per-reader offsets and no
//! acknowledgement. Pattern 2 (request/response coordination —
//! `await_approval`) builds on this primitive but ships its API
//! distinctly in S13-B-5.
//!
//! ## Invariants
//!
//! - **Append-only**: writers never seek; concurrent writers are safe
//!   for `< PIPE_BUF` (4 KB) lines via POSIX `O_APPEND` atomicity.
//!   `QueueMessage::serialized_size()` lets callers self-police.
//! - **Forward-only iteration**: `JsonlQueueReader` exposes a
//!   `since_offset` cursor; callers persist their own offset (the log
//!   never tracks who's read what).
//! - **Pure I/O**: this module ships in `neurogrim-core` because the
//!   shape is universal; the dashboard, MCP server, and CLI all wrap
//!   it differently. No HTTP, no async, no tokio.
//! - **Malformed-line tolerance**: a corrupt line never wedges a
//!   reader; iteration logs `tracing::warn!` and skips. Same
//!   discipline as `calibration_ledger::JsonlIter` (the prior art
//!   this module inherits from).
//!
//! ## Reserved namespace
//!
//! Topic IDs of the form `_neurogrim/<name>` are RESERVED for system
//! topics (e.g., `_neurogrim/approvals`, `_neurogrim/notifications`).
//! Adopters MUST NOT publish into them. [`Topic::is_reserved`] +
//! [`Topic::is_valid_adopter_topic`] are the syntactic checks; the
//! authoritative enforcement is in `neurogrim doctor` (S13-B-7).
//!
//! ## Schema
//!
//! ```json
//! {
//!   "id":          "<uuid v4>",
//!   "topic":       "<scope>/<name>",
//!   "payload":     {…arbitrary JSON…},
//!   "produced_at": "2026-04-29T13:42:18Z",
//!   "priority":    "low" | "normal" | "high",
//!   "expires_at":  "2026-04-30T13:42:18Z"      // optional
//! }
//! ```

use anyhow::{bail, Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;
use uuid::Uuid;

// ── Constants ─────────────────────────────────────────────────────────

/// Reserved topic prefix. Adopters MUST NOT publish into topics
/// starting with this string.
pub const RESERVED_PREFIX: &str = "_neurogrim/";

// ── Public types ──────────────────────────────────────────────────────

/// Single message on the bus. Mirrors the schema sketched in the S13
/// epic (`epics/S13-agent-coordination-bus.md` §S13-B-1).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct QueueMessage {
    /// UUID v4. Generated by [`QueueMessage::new`]. Stable across
    /// retries — operators replaying a message keep the same id.
    pub id: Uuid,
    /// Topic name. See [`Topic`] for namespace rules.
    pub topic: String,
    /// Free-form payload. The bus is payload-agnostic; consumers
    /// negotiate shape per-topic (typed agents declare schemas in
    /// `queue-config.yaml`; raw consumers handle untyped JSON).
    pub payload: serde_json::Value,
    /// RFC3339 UTC timestamp set by [`QueueMessage::new`].
    pub produced_at: DateTime<Utc>,
    /// Coarse priority classification. Readers may choose to honor or
    /// ignore. Default: [`Priority::Normal`].
    pub priority: Priority,
    /// Optional expiry. Readers SHOULD filter out expired messages.
    /// `None` = never expires.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_at: Option<DateTime<Utc>>,
}

/// Coarse priority enum. Three buckets — finer gradations would be
/// over-engineering for a v1 bus.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum Priority {
    Low,
    Normal,
    High,
}

impl Default for Priority {
    fn default() -> Self {
        Priority::Normal
    }
}

impl QueueMessage {
    /// Build a new message with a fresh UUID v4 + current UTC
    /// timestamp.
    pub fn new(topic: impl Into<String>, payload: serde_json::Value) -> Self {
        Self {
            id: Uuid::new_v4(),
            topic: topic.into(),
            payload,
            produced_at: Utc::now(),
            priority: Priority::Normal,
            expires_at: None,
        }
    }

    /// Builder-style priority setter.
    pub fn with_priority(mut self, priority: Priority) -> Self {
        self.priority = priority;
        self
    }

    /// Builder-style expiry setter.
    pub fn with_expires_at(mut self, expires_at: DateTime<Utc>) -> Self {
        self.expires_at = Some(expires_at);
        self
    }

    /// True iff the message is past its `expires_at`. `None` →
    /// never expired.
    pub fn is_expired(&self, now: DateTime<Utc>) -> bool {
        match self.expires_at {
            Some(exp) => now >= exp,
            None => false,
        }
    }

    /// Approximate serialized line size in bytes. Callers writing
    /// directly to JSONL files use this to self-police the
    /// PIPE_BUF (~4 KB) atomicity boundary — messages above the
    /// boundary lose concurrent-write atomicity guarantees.
    pub fn serialized_size(&self) -> usize {
        // +1 for the trailing newline that `append` adds.
        serde_json::to_string(self).map(|s| s.len() + 1).unwrap_or(0)
    }
}

// ── Topic namespace helpers ───────────────────────────────────────────

/// Stateless helpers for topic-name validation. The bus doesn't
/// own a registry of topics (creation is implicit on first
/// publish); these helpers exist so writers + the doctor check can
/// agree on shape.
pub struct Topic;

impl Topic {
    /// True iff the topic is in the reserved system-namespace.
    /// Reserved names are `_neurogrim/<lowercase-kebab>`.
    pub fn is_reserved(name: &str) -> bool {
        name.starts_with(RESERVED_PREFIX)
    }

    /// True iff the topic is a syntactically-valid adopter-defined
    /// name. Rules:
    /// - NOT in the reserved namespace
    /// - lowercase ASCII alphanumeric + `-` + `/`
    /// - at least one character before the first `/`
    /// - no leading or trailing `/` or `-`
    /// - no consecutive separators (`//`, `--`)
    ///
    /// `neurogrim doctor` enforces this against `queue-config.yaml`
    /// at validation time.
    pub fn is_valid_adopter_topic(name: &str) -> bool {
        if Self::is_reserved(name) {
            return false;
        }
        if name.is_empty() {
            return false;
        }
        let bytes = name.as_bytes();
        if bytes.first() == Some(&b'/')
            || bytes.last() == Some(&b'/')
            || bytes.first() == Some(&b'-')
            || bytes.last() == Some(&b'-')
        {
            return false;
        }
        // Disallow consecutive separators. Allowed character class:
        // ASCII lowercase letters, digits, `-`, `/`.
        let mut prev = b' ';
        for &b in bytes {
            let ok = matches!(b, b'a'..=b'z' | b'0'..=b'9' | b'-' | b'/');
            if !ok {
                return false;
            }
            if (b == b'/' || b == b'-') && (prev == b'/' || prev == b'-') {
                return false;
            }
            prev = b;
        }
        true
    }

    /// True iff the topic is either a reserved system topic OR a
    /// valid adopter topic. Useful for code paths that legitimately
    /// publish either (e.g., the dashboard's bus service).
    pub fn is_valid(name: &str) -> bool {
        Self::is_reserved(name) || Self::is_valid_adopter_topic(name)
    }
}

// ── Append-only writer ────────────────────────────────────────────────

/// Append a single message as one JSONL line. Atomic for
/// `serialized_size() < PIPE_BUF` (4 KB on POSIX); concurrent
/// writers within that bound never interleave.
///
/// Callers needing `produced_at` to be set by the bus rather than
/// the caller should use [`QueueMessage::new`] before calling.
pub fn append(path: &Path, msg: &QueueMessage) -> Result<()> {
    if !Topic::is_valid(&msg.topic) {
        bail!(
            "queue: invalid topic name {:?} — adopters use lowercase \
             kebab-case `<scope>/<name>`; system topics use `_neurogrim/<name>`",
            msg.topic
        );
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .context("queue: create parent dir for ledger")?;
    }
    let line = serde_json::to_string(msg).context("queue: serialize message")?;
    if line.contains('\n') {
        bail!("queue: serialized message contained a newline (multi-line JSON?)");
    }
    let mut f = OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .with_context(|| format!("queue: open {} for append", path.display()))?;
    writeln!(f, "{line}").context("queue: write line")?;
    f.flush().context("queue: flush")?;
    Ok(())
}

// ── Reader ────────────────────────────────────────────────────────────

/// Read messages from a JSONL queue file, starting at the Nth line
/// (zero-indexed; `since_offset` is line-number, not byte-offset).
///
/// Behavior:
/// - Missing file → empty iterator (the queue hasn't received any
///   messages yet; consumer offset 0 is well-defined).
/// - I/O failure on read → error returned from
///   [`JsonlQueueReader::open`]; iteration is infallible.
/// - Malformed line → logged at `tracing::warn!` + skipped (matches
///   the calibration-ledger reader's posture).
/// - Expired messages: NOT filtered by the reader; consumers who
///   care call [`QueueMessage::is_expired`].
pub struct JsonlQueueReader {
    /// One entry per non-empty line in the file at construction
    /// time. Snapshot semantics — concurrent appends after `open`
    /// won't appear in this iterator. Re-open to drain new entries.
    messages: Vec<QueueMessage>,
}

impl JsonlQueueReader {
    /// Open + parse all lines. Returns an iterator-shaped wrapper
    /// you can call `iter_from(offset)` on.
    pub fn open(path: &Path) -> Result<Self> {
        let raw = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return Ok(Self { messages: Vec::new() });
            }
            Err(e) => {
                return Err(e).with_context(|| {
                    format!("queue: read {} for iteration", path.display())
                });
            }
        };
        let mut messages = Vec::new();
        for (idx, line) in raw.lines().enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            match serde_json::from_str::<QueueMessage>(line) {
                Ok(m) => messages.push(m),
                Err(e) => {
                    tracing::warn!(
                        "queue: malformed JSONL line {} in {}: {} — skipping",
                        idx + 1,
                        path.display(),
                        e
                    );
                }
            }
        }
        Ok(Self { messages })
    }

    /// Total parseable messages snapshotted at `open` time.
    pub fn len(&self) -> usize {
        self.messages.len()
    }

    pub fn is_empty(&self) -> bool {
        self.messages.is_empty()
    }

    /// All messages whose offset (line index, 0-based) is `>= since`.
    /// Useful for the consumer-resume pattern: persist last-seen
    /// offset, call `iter_from(last + 1)` next time.
    pub fn iter_from(&self, since: usize) -> impl Iterator<Item = &QueueMessage> {
        let start = since.min(self.messages.len());
        self.messages[start..].iter()
    }

    /// Consume the reader and return the underlying snapshot. Useful
    /// for callers wanting to take ownership of the entries.
    pub fn into_messages(self) -> Vec<QueueMessage> {
        self.messages
    }

    /// All messages NOT past their expiry as of `now`.
    pub fn live_messages(&self, now: DateTime<Utc>) -> impl Iterator<Item = &QueueMessage> {
        self.messages.iter().filter(move |m| !m.is_expired(now))
    }

    /// Most recent N messages (oldest first within the slice).
    /// Equivalent to `tail -n` on the underlying file but safe across
    /// malformed-line skips.
    pub fn tail(&self, count: usize) -> &[QueueMessage] {
        let start = self.messages.len().saturating_sub(count);
        &self.messages[start..]
    }
}

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Duration;
    use serde_json::json;
    use tempfile::TempDir;

    fn p(dir: &TempDir, name: &str) -> std::path::PathBuf {
        dir.path().join(name)
    }

    #[test]
    fn message_new_sets_id_and_timestamp() {
        let m = QueueMessage::new("ng/test", json!({"k": "v"}));
        assert!(!m.id.is_nil());
        assert_eq!(m.topic, "ng/test");
        assert_eq!(m.priority, Priority::Normal);
        assert_eq!(m.expires_at, None);
        assert!(m.payload["k"] == json!("v"));
    }

    #[test]
    fn message_builder_sets_priority_and_expiry() {
        let when = Utc::now() + Duration::seconds(3600);
        let m = QueueMessage::new("ng/test", json!({}))
            .with_priority(Priority::High)
            .with_expires_at(when);
        assert_eq!(m.priority, Priority::High);
        assert_eq!(m.expires_at, Some(when));
    }

    #[test]
    fn append_then_read_round_trips() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng-test.jsonl");
        let m1 = QueueMessage::new("ng/test", json!({"i": 1}));
        let m2 = QueueMessage::new("ng/test", json!({"i": 2}));
        append(&path, &m1).unwrap();
        append(&path, &m2).unwrap();
        let r = JsonlQueueReader::open(&path).unwrap();
        let read: Vec<_> = r.iter_from(0).cloned().collect();
        assert_eq!(read.len(), 2);
        assert_eq!(read[0], m1);
        assert_eq!(read[1], m2);
    }

    #[test]
    fn append_creates_parent_dirs() {
        let dir = TempDir::new().unwrap();
        let nested = dir.path().join("sub1").join("sub2").join("topic.jsonl");
        let m = QueueMessage::new("ng/test", json!({}));
        append(&nested, &m).unwrap();
        assert!(nested.is_file());
    }

    #[test]
    fn read_missing_file_returns_empty() {
        let dir = TempDir::new().unwrap();
        let r = JsonlQueueReader::open(&p(&dir, "never-written.jsonl")).unwrap();
        assert!(r.is_empty());
        assert_eq!(r.len(), 0);
        assert_eq!(r.iter_from(0).count(), 0);
    }

    #[test]
    fn iter_from_skips_consumed_offsets() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng.jsonl");
        for i in 0..5 {
            append(&path, &QueueMessage::new("ng/test", json!({"i": i}))).unwrap();
        }
        let r = JsonlQueueReader::open(&path).unwrap();
        assert_eq!(r.iter_from(0).count(), 5);
        assert_eq!(r.iter_from(2).count(), 3);
        assert_eq!(r.iter_from(5).count(), 0);
        // out-of-range gracefully clamps to empty
        assert_eq!(r.iter_from(99).count(), 0);
    }

    #[test]
    fn malformed_line_is_skipped_not_fatal() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng.jsonl");
        let valid = QueueMessage::new("ng/test", json!({"ok": true}));
        append(&path, &valid).unwrap();
        // Inject a corrupt line directly.
        std::fs::write(
            &path,
            format!(
                "{}\nnot-valid-json\n{}\n",
                serde_json::to_string(&valid).unwrap(),
                serde_json::to_string(
                    &QueueMessage::new("ng/test", json!({"ok": true}))
                )
                .unwrap()
            ),
        )
        .unwrap();
        let r = JsonlQueueReader::open(&path).unwrap();
        // Two valid messages, the corrupt one swallowed.
        assert_eq!(r.len(), 2);
    }

    #[test]
    fn empty_lines_are_skipped() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng.jsonl");
        let m = QueueMessage::new("ng/test", json!({}));
        let line = serde_json::to_string(&m).unwrap();
        // File with leading + trailing + interleaved blank lines.
        std::fs::write(&path, format!("\n\n{line}\n\n{line}\n\n")).unwrap();
        let r = JsonlQueueReader::open(&path).unwrap();
        assert_eq!(r.len(), 2);
    }

    #[test]
    fn is_expired_handles_none_some_past_some_future() {
        let now = Utc::now();
        let m_no_exp = QueueMessage::new("ng/t", json!({}));
        assert!(!m_no_exp.is_expired(now));
        let m_past = QueueMessage::new("ng/t", json!({}))
            .with_expires_at(now - Duration::seconds(60));
        assert!(m_past.is_expired(now));
        let m_future = QueueMessage::new("ng/t", json!({}))
            .with_expires_at(now + Duration::seconds(60));
        assert!(!m_future.is_expired(now));
    }

    #[test]
    fn live_messages_filters_expired() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng.jsonl");
        let now = Utc::now();
        let live = QueueMessage::new("ng/t", json!({"k":"live"}));
        let expired = QueueMessage::new("ng/t", json!({"k":"expired"}))
            .with_expires_at(now - Duration::seconds(60));
        append(&path, &live).unwrap();
        append(&path, &expired).unwrap();
        let r = JsonlQueueReader::open(&path).unwrap();
        let live: Vec<_> = r.live_messages(now).collect();
        assert_eq!(live.len(), 1);
        assert_eq!(live[0].payload["k"], "live");
    }

    #[test]
    fn tail_returns_last_n_messages() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng.jsonl");
        for i in 0..10 {
            append(&path, &QueueMessage::new("ng/t", json!({"i": i}))).unwrap();
        }
        let r = JsonlQueueReader::open(&path).unwrap();
        let tail3 = r.tail(3);
        assert_eq!(tail3.len(), 3);
        assert_eq!(tail3[0].payload["i"], 7);
        assert_eq!(tail3[2].payload["i"], 9);
        // tail(N) >= total returns the full slice.
        assert_eq!(r.tail(50).len(), 10);
        assert_eq!(r.tail(0).len(), 0);
    }

    // ── Topic namespace tests ────────────────────────────────────

    #[test]
    fn reserved_namespace_recognized() {
        assert!(Topic::is_reserved("_neurogrim/approvals"));
        assert!(Topic::is_reserved("_neurogrim/notifications"));
        assert!(!Topic::is_reserved("ng/approvals"));
        assert!(!Topic::is_reserved(""));
    }

    #[test]
    fn adopter_topic_validation_accepts_kebab_paths() {
        assert!(Topic::is_valid_adopter_topic("ng/test"));
        assert!(Topic::is_valid_adopter_topic("pc-state/alerts"));
        assert!(Topic::is_valid_adopter_topic("a"));
        assert!(Topic::is_valid_adopter_topic("scope/sub-name/leaf"));
    }

    #[test]
    fn adopter_topic_validation_rejects_reserved_and_malformed() {
        // Reserved namespace
        assert!(!Topic::is_valid_adopter_topic("_neurogrim/approvals"));
        // Empty / leading / trailing separators
        assert!(!Topic::is_valid_adopter_topic(""));
        assert!(!Topic::is_valid_adopter_topic("/leading"));
        assert!(!Topic::is_valid_adopter_topic("trailing/"));
        assert!(!Topic::is_valid_adopter_topic("-leading-dash"));
        assert!(!Topic::is_valid_adopter_topic("trailing-dash-"));
        // Consecutive separators
        assert!(!Topic::is_valid_adopter_topic("scope//name"));
        assert!(!Topic::is_valid_adopter_topic("scope--name"));
        // Disallowed characters
        assert!(!Topic::is_valid_adopter_topic("Scope/name")); // uppercase
        assert!(!Topic::is_valid_adopter_topic("scope/Name")); // uppercase
        assert!(!Topic::is_valid_adopter_topic("scope:name")); // `:` reserved per spec
        assert!(!Topic::is_valid_adopter_topic("scope.name")); // `.` not allowed
        assert!(!Topic::is_valid_adopter_topic("scope name")); // space
    }

    #[test]
    fn is_valid_accepts_either_reserved_or_adopter() {
        assert!(Topic::is_valid("_neurogrim/notifications"));
        assert!(Topic::is_valid("pc-state/alerts"));
        assert!(!Topic::is_valid("Bad/Name"));
    }

    #[test]
    fn append_rejects_invalid_topic() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "ng.jsonl");
        let msg = QueueMessage::new("Bad/Name", json!({}));
        let res = append(&path, &msg);
        assert!(res.is_err());
        assert!(res
            .unwrap_err()
            .to_string()
            .contains("invalid topic name"));
        // File should not have been touched.
        assert!(!path.exists());
    }

    #[test]
    fn append_accepts_reserved_topic_for_internal_use() {
        let dir = TempDir::new().unwrap();
        let path = p(&dir, "approvals.jsonl");
        let msg = QueueMessage::new("_neurogrim/approvals", json!({"action_id": "xyz"}));
        append(&path, &msg).unwrap();
        let r = JsonlQueueReader::open(&path).unwrap();
        assert_eq!(r.len(), 1);
    }

    #[test]
    fn priority_serializes_lowercase() {
        let m = QueueMessage::new("ng/t", json!({})).with_priority(Priority::High);
        let s = serde_json::to_string(&m).unwrap();
        assert!(s.contains("\"priority\":\"high\""));
    }

    #[test]
    fn priority_default_is_normal() {
        assert_eq!(Priority::default(), Priority::Normal);
    }

    #[test]
    fn serialized_size_is_reasonable_for_typical_messages() {
        let m = QueueMessage::new("ng/test", json!({"some": "small payload"}));
        let size = m.serialized_size();
        assert!(size > 100, "size too small: {size}"); // uuid + ts alone are >100
        assert!(size < 4096, "typical message must fit under PIPE_BUF: {size}");
    }
}
