// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset of the peer's Agent Card that's interesting to show in the
 * dashboard. The full card is intentionally not surfaced — operators
 * who need it can run `neurogrim a2a-discover <url>`.
 */
export type AgentCardExcerptDto = { id: string, name: string, version: string, interface_version: string, schema_version: string, 
/**
 * "http+sse" | "json-rpc" — peer's declared transport protocol.
 */
transport_protocol: string, 
/**
 * Topology role from the Agent Card (`project` | `ecosystem` |
 * `local` | `external`). None when the peer didn't declare one.
 */
topology_role: string | null, 
/**
 * Topology parent id when declared (typical for child Brains).
 */
topology_parent_id: string | null, };
