// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalRequestView } from "./ApprovalRequestView";
import type { ApprovalResolutionView } from "./ApprovalResolutionView";

/**
 * Response body of `GET /api/brains/:brain_id/approvals` — pending
 * + recently-resolved autonomy approvals. Backs the new
 * `/brains/:id/approvals` page; agents calling mutation tools that
 * resolve to `Approve` autonomy land entries on
 * `_neurogrim/approvals` and operators resolve them here.
 */
export type ApprovalsPageResponse = { 
/**
 * Approval requests that haven't been resolved yet. Joined
 * from `_neurogrim/approvals` minus anything in
 * `_neurogrim/approval-resolutions`. Newest-first.
 */
pending: Array<ApprovalRequestView>, 
/**
 * Recently-resolved approvals. Newest-first; capped at 50.
 */
recent_resolutions: Array<ApprovalResolutionView>, };
