// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalResolutionView = { action_id: string, 
/**
 * `"approve"` | `"deny"` (others surfaced for forward-compat).
 */
decision: string, operator: string | null, decided_at: string, };
