// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalRequestView = { action_id: string, tool: string, action_type: string, requested_at: string, };
