// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Brain in the federation tree.
 */
export type BrainListItemDto = { 
/**
 * kebab-case id (URL-safe). Derived from `meta.project` or
 * project_root basename. Stable across server restarts.
 */
id: string, 
/**
 * Human-readable name from `meta.project` (or the id when that
 * field is absent).
 */
display_name: string, 
/**
 * Filesystem path to the project root.
 */
project_root: string, 
/**
 * id of the parent Brain in the federation tree, or `null` for
 * the host.
 */
parent_id: string | null, 
/**
 * 0 for the host, 1 for direct children, 2 for grandchildren.
 */
depth: number, };
