// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrainListItemDto } from "./BrainListItemDto";

/**
 * Response body of `GET /api/brains` — every Brain reachable from
 * the host registry, transitively walked through `config.children`.
 *
 * The dashboard uses this to populate the AppShell's Brain
 * switcher and to validate the `:brain_id` URL path segment.
 */
export type BrainsListResponse = { self_id: string, brains: Array<BrainListItemDto>, };
