// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/brains/:brain_id/config-file/:name` —
 * raw text + presence for the operator-facing read-only Settings
 * viewers. Hardcoded allowlist (culture.yaml, queue-config.yaml)
 * keeps the surface tight.
 */
export type ConfigFileResponse = { 
/**
 * Logical name of the file (matches the URL path segment).
 */
name: string, 
/**
 * True when the file exists on disk.
 */
present: boolean, 
/**
 * Resolved on-disk path (for operator diagnostics).
 */
path: string, 
/**
 * File text when `present`. None on absent or read-error.
 */
text: string | null, 
/**
 * Error message when read failed despite the file existing.
 * `present: false` + `error: None` means the file simply
 * doesn't exist (the common case for adopters who haven't
 * authored the manifest yet).
 */
error: string | null, };
