// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body of `POST /api/brains/:brain_id/dashboard-pages/:name`.
 * v1 is name-only — operator picks an icon + adds widgets later via
 * the Add Widget flow (deferred).
 */
export type CreateCustomPageRequest = { 
/**
 * Optional title shown in the sidebar; defaults to the page id.
 */
title: string | null, };
