// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetSpec } from "./WidgetSpec";

/**
 * Request body of `PUT /api/brains/:brain_id/dashboard-pages/:name/layout`.
 *
 * **S15-C-6 v2:** lets operators save a custom page's widget list
 * from the dashboard. Same shape as the v3.4 single-page
 * `DashboardLayoutRequest` (a list of `WidgetSpec`s); the only
 * difference is the URL path scopes the write to a specific
 * custom page within the v2 multi-page config.
 */
export type CustomPageLayoutRequest = { widgets: Array<WidgetSpec>, };
