// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of the `POST` + `DELETE` page endpoints.
 */
export type CustomPageMutationResponse = { ok: boolean, name: string, };
