// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetSpec } from "./WidgetSpec";

/**
 * Body of `PUT /api/brains/:id/dashboard-layout`. The operator
 * (or an agent) submits widgets only — `schema_version` is
 * pinned by the server, `brain_id` comes from the URL path,
 * `is_default` is computed (always `false` after a successful
 * PUT — the saved layout IS the operator's intent).
 */
export type DashboardLayoutRequest = { widgets: Array<WidgetSpec>, };
