// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetSpec } from "./WidgetSpec";

/**
 * v2 multi-page config. Replaces v3.4's single
 * `DashboardLayoutResponse` for adopters who opt into the new
 * shape; the old format still works via [`read_dashboard_pages`]'s
 * backward-compat path.
 */
export type DashboardPagesConfig = { schema_version: string, brain_id: string, 
/**
 * Per-page widget content. Keys are page IDs (`overview`,
 * `custom-pc-state`, etc.); values are the widget lists. A
 * page with no entry in this map renders empty (custom pages)
 * or falls back to its built-in default (Overview).
 */
pages: { [key in string]?: Array<WidgetSpec> }, 
/**
 * Sidebar ordering. Front-of-list = top-of-sidebar. Built-in
 * pages appear in this list when the operator wants to
 * reorder them; missing built-ins use their default position.
 */
page_order: Array<string>, };
