// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetSpec } from "./WidgetSpec";

/**
 * Body of `GET /api/brains/:id/dashboard-layout`.
 */
export type DashboardLayoutResponse = { schema_version: string, brain_id: string, 
/**
 * True when the layout came from `dashboard-layout.json` on
 * disk. False when the response is the synthesized default
 * (no file present) — the frontend renders a "this is the
 * default; click 'Customize' to edit" hint in that case.
 */
is_default: boolean, widgets: Array<WidgetSpec>, };
