// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `DELETE /api/brains/:id/secrets/:secret_id`.
 */
export type DeleteSecretResponse = { brain_id: string, secret_id: string, 
/**
 * True iff a stored value existed and was removed. False
 * when no value was present (idempotent delete).
 */
removed: boolean, };
