// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainListItemDto } from "./DomainListItemDto";

/**
 * Response body of `GET /api/domains` — the sortable list view that
 * powers the Domains page table.
 */
export type DomainsListResponse = { domains: Array<DomainListItemDto>, };
