// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingDto } from "./FindingDto";
import type { HistoryPointDto } from "./HistoryPointDto";

/**
 * Response body of `GET /api/domains/:name` — the drill-in detail.
 */
export type DomainDetailResponse = { name: string, display_name: string, weight: number, raw_score: number, effective_score: number, confidence: number, trajectory_class: string, trajectory_velocity: number, trajectory_samples: number, 
/**
 * Operator-supplied sensor authoring intent — the
 * `_todo_<name>` placeholder on the domain definition (set
 * via `domain new --sensor-intent`). Useful when the sensor
 * hasn't been written yet. None when absent.
 */
sensor_intent: string | null, 
/**
 * CMDB findings array (preserved verbatim from the on-disk
 * envelope). Empty array when no CMDB exists or no findings
 * were emitted.
 */
findings: Array<FindingDto>, 
/**
 * Score-history sparkline data. Each entry is one tick. May
 * be empty (Brain just initialized) or sparse.
 */
history: Array<HistoryPointDto>, 
/**
 * Filesystem path to the CMDB JSON, displayed for operator
 * awareness ("which file would I edit to refresh this").
 */
cmdb_path: string, 
/**
 * CMDB `meta.updated_at` if present; None when no CMDB on disk.
 */
last_updated: string | null, };
