// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-domain summary used in `OverviewResponse.strongest_signals`
 * and the Domains-page table. The full per-domain detail (CMDB
 * findings, history) is fetched separately via
 * `GET /api/domains/:name`.
 */
export type DomainSignalDto = { name: string, 
/**
 * Humanized display (from registry.principle_map; falls back
 * to the kebab-case name).
 */
display_name: string, effective_score: number, confidence: number, weight: number, };
