// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the domains table. Includes everything sortable from
 * the page UI (name, weight, scores, confidence, trajectory).
 */
export type DomainListItemDto = { name: string, display_name: string, weight: number, raw_score: number, effective_score: number, confidence: number, 
/**
 * Trajectory classification at the per-domain level. One of
 * "improving" | "degrading" | "stable" | "volatile" | "no-data".
 */
trajectory_class: string, trajectory_velocity: number, trajectory_samples: number, 
/**
 * CMDB `meta.updated_at` (ISO 8601 UTC). `None` when the CMDB
 * is missing on disk (the domain registers but no sensor has
 * produced a CMDB yet — the v3.2 stub-domain pattern).
 */
last_updated: string | null, };
