// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/explain/:topic` — the markdown text of
 * a bundled `neurogrim explain` topic, returned verbatim. Used by
 * the Settings page's `?` HelpIcon to render the relevant topic
 * in a modal.
 */
export type ExplainTopicResponse = { name: string, content: string, };
