// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerDto } from "./PeerDto";
import type { SelfBrainDto } from "./SelfBrainDto";

/**
 * Response body of `GET /api/federation` — the Brain's view of its
 * federation: who it is, who its A2A peers are, and whether each
 * peer is currently reachable.
 *
 * The dashboard renders this as a topology diagram (self in center,
 * peers around) plus a per-peer detail panel.
 */
export type FederationResponse = { self_brain: SelfBrainDto, peers: Array<PeerDto>, 
/**
 * Schema version of the registry — surfaced so the page can
 * warn if the operator's registry predates `read_only` support
 * (anything before 2.1).
 */
registry_schema_version: string, };
