// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CMDB finding entry. Schema mirrors the canonical
 * `cmdb-envelope-v1.schema.json` finding shape.
 */
export type FindingDto = { name: string, status: string, points: number, 
/**
 * Optional human-readable explanation. Sensors SHOULD include
 * it on warnings/errors; for "pass" findings it's commonly
 * absent.
 */
detail: string | null, };
