// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hat declaration. Mirrors registry's `config.hats.<name>`
 * minus the scoring internals (`domain_multipliers`, `suggest_when`)
 * — the dashboard only needs the picker-facing surface.
 */
export type HatDto = { 
/**
 * Hat id (kebab-case, e.g. "engineer", "reviewer"). The
 * synthetic "default" entry uses the literal string `"default"`.
 */
name: string, 
/**
 * Human-readable description from the registry (or a built-in
 * description for the synthetic default entry).
 */
description: string, 
/**
 * True for the synthetic "default" entry — operators see it
 * at the top of the picker as a way to clear the lens.
 */
is_default: boolean, };
