// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HatDto } from "./HatDto";

/**
 * Response body of `GET /api/hats` — every hat declared in the
 * registry, plus a synthetic "default" entry the picker uses to
 * surface the un-hatted lens.
 *
 * The dashboard renders this as a dropdown in the AppShell. When
 * the user picks a hat, every score-aware query re-fetches with
 * `?hat=<name>` so the Brain output is filtered through that
 * hat's `domain_multipliers`.
 */
export type HatsResponse = { hats: Array<HatDto>, };
