// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/health`. The simplest endpoint —
 * proves the wire-format pipeline works. Returns ok=true plus a
 * few diagnostic fields the frontend can use to detect server/
 * client version drift.
 */
export type HealthResponse = { ok: boolean, registry_path: string, 
/**
 * Server version (matches the dashboard binary's
 * `CARGO_PKG_VERSION`). Frontends bundled at v3.4 connecting
 * to a v3.5 server can warn the operator.
 */
version: string, };
