// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point in a domain's score-history sparkline.
 */
export type HistoryPointDto = { 
/**
 * ISO 8601 UTC timestamp.
 */
scored_at: string, score: number, confidence: number, };
