// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry from the invocation ledger, surfaced as a Logs
 * timeline event.
 *
 * Mirrors the on-disk JSONL line shape but typed + selectively
 * projected — the ledger may grow new fields (subtype, hook
 * emitter, etc.) over time and the wire format stays tight.
 */
export type InvocationLedgerEntry = { 
/**
 * RFC3339 timestamp from the ledger row's `ts` field.
 */
ts: string, 
/**
 * Entry type — currently always `"skill"` per
 * `record-skill-invocation.sh`. The schema reserves the field
 * for future hook variants (mcp_call, command, etc.).
 */
entry_type: string, 
/**
 * Skill (or hook) name. `None` if the ledger row was
 * malformed; we keep the row visible rather than silently
 * dropping it so operators can spot drift.
 */
name: string | null, 
/**
 * Claude Code session id when present (post-2026-04-22 ledger
 * entries carry it; older ones may not).
 */
session_id: string | null, 
/**
 * Claude Code tool-use invocation id when present.
 */
invocation_id: string | null, };
