// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvocationLedgerEntry } from "./InvocationLedgerEntry";

/**
 * Response body of `GET /api/brains/:id/logs/invocation-ledger`.
 */
export type InvocationLedgerResponse = { 
/**
 * Path the ledger was read from. Helps operators correlate
 * the timeline with their on-disk audit trail.
 */
ledger_path: string, 
/**
 * True when the file exists. False = empty timeline (the
 * invocation hook isn't installed, or the project has zero
 * recorded skill invocations).
 */
present: boolean, 
/**
 * Total non-empty lines parsed from the ledger, before the
 * limit was applied. Surfaces "ledger has 12,408 entries; we
 * returned the most recent 50" telemetry to the operator.
 */
total_entries: number, 
/**
 * Entries newest-first, capped at the request's limit.
 */
entries: Array<InvocationLedgerEntry>, };
