// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeOp } from "./ChangeOp";

/**
 * Single keypath-level change. Mirrors the payload field shape
 * agents subscribed to `_neurogrim/config-changes` will see.
 */
export type KeypathChange = { 
/**
 * Dotted path with array brackets, e.g. `config.autonomy.action_types.edit-code.default_level`
 * or `widgets[2].size`. Empty path becomes `"$"` for top-level
 * scalar replacements (defensive — our domain's roots are
 * always objects).
 */
path: string, op: ChangeOp, 
/**
 * Prior value (None for `add`).
 */
before: unknown, 
/**
 * New value (None for `remove`).
 */
after: unknown, };
