// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainSignalDto } from "./DomainSignalDto";
import type { RecommendationDto } from "./RecommendationDto";

/**
 * Lightweight, prose-tuned summary of a Brain's current state,
 * powering the dashboard's Overview page.
 *
 * Distinct from `neurogrim_core::AgentOutput`: this DTO is
 * dashboard-curated (top 3 recs, top 3 strongest signals,
 * federation peer count rather than full peer list) — the goal
 * is "what does a human want to see on first glance," not
 * "every spec'd field." The full AgentOutput is available via
 * `GET /api/agent` for consumers that need it.
 */
export type OverviewResponse = { 
/**
 * Display name for the Brain (from `meta.description` first
 * sentence; falls back to project_root basename).
 */
project_label: string, 
/**
 * Filesystem path to the registry, surfaced for operator
 * awareness (which Brain is being shown).
 */
project_root: string, 
/**
 * Total declared domains.
 */
domain_count: number, 
/**
 * Subset that are weighted (weight > 0).
 */
weighted_count: number, 
/**
 * Subset that are advisory (weight == 0).
 */
advisory_count: number, 
/**
 * Unified score 0..=100. None when the Brain is all-advisory
 * (in that case the score is structurally 0 / N/A).
 */
score: number | null, 
/**
 * Weighted-mean confidence 0..=100 across non-advisory
 * domains. None paired with `score: None` for all-advisory.
 */
confidence: number | null, 
/**
 * Trajectory classification ("improving" | "degrading" |
 * "stable" | "volatile" | "no-data"). Stringly-typed at the
 * wire to keep the frontend simple; mapped to TrajectoryKind
 * in TS.
 */
trajectory_class: string, 
/**
 * Trajectory velocity (signed; positive = improving).
 */
trajectory_velocity: number, 
/**
 * Number of score-history samples observed.
 */
trajectory_samples: number, 
/**
 * Top recommendations (up to 3).
 */
top_recommendations: Array<RecommendationDto>, 
/**
 * Top strongest signals (up to 3 highest effective scores).
 */
strongest_signals: Array<DomainSignalDto>, 
/**
 * Count of declared federation peers.
 */
federation_peer_count: number, };
