// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/brains/:id/peers/:peer_name/log`.
 */
export type PeerLogResponse = { 
/**
 * Resolved on-disk path. Helps operators correlate the modal
 * with what they'd see in `tail -f` outside the dashboard.
 */
log_path: string, present: boolean, 
/**
 * Total file size in bytes. `None` when `present: false`.
 * Surfaces "the tail you see is the last 256 KB of a 12 MB
 * file" telemetry without requiring a full read.
 */
total_size_bytes: bigint | null, 
/**
 * True when [`PEER_LOG_TAIL_BYTES`] truncation discarded older
 * content. The frontend can hint that the operator is seeing
 * only the most recent slice.
 */
truncated: boolean, 
/**
 * Lines, oldest-first within the returned slice. May contain a
 * partial leading line stripped (we discard the first line
 * when seeking into the middle of one) so all lines are whole.
 */
lines: Array<string>, };
