// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status taxonomy for federation peers. Stringly-typed at the wire
 * (matches the rest of this module's stringly-typed enums) and
 * re-narrowed in TS via a discriminated union.
 */
export type PeerStatusDto = { 
/**
 * One of "alive" | "unreachable" | "unprobed" | "disabled".
 */
kind: string, 
/**
 * Operator-facing detail (error message, "subprocess transport",
 * etc.). Empty when the status is self-explanatory.
 */
message: string, };
