// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCardExcerptDto } from "./AgentCardExcerptDto";
import type { PeerStatusDto } from "./PeerStatusDto";

/**
 * One declared A2A / subprocess peer in the registry's
 * `config.children` block, augmented with a freshness probe for A2A
 * peers (best-effort, capped timeout).
 */
export type PeerDto = { 
/**
 * kebab-case peer id (key under `config.children`).
 */
name: string, display_name: string, 
/**
 * Either "a2a" or "subprocess" — selects how the parent reaches
 * this peer. Subprocess peers are NOT probed; their status is
 * always `unprobed`.
 */
transport: string, 
/**
 * A2A endpoint URL when transport == "a2a"; `None` otherwise.
 */
a2a_endpoint: string | null, 
/**
 * Filesystem path to the child Brain (subprocess transport) or
 * the relative path declared alongside the A2A endpoint. May be
 * absent for purely-remote peers.
 */
brain_path: string | null, weight: number, 
/**
 * Read-only sibling per LSP-Brains v2.1+ (does not influence the
 * parent's score; observation only).
 */
read_only: boolean, enabled: boolean, 
/**
 * Freshness probe outcome. `unprobed` for disabled or non-A2A
 * peers; `alive` / `unreachable` for A2A peers we tried to reach.
 */
status: PeerStatusDto, 
/**
 * When status == "alive", the relevant fields from the peer's
 * Agent Card. None on probe failure or non-A2A transports.
 */
agent_card: AgentCardExcerptDto | null, };
