// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A ledger entry as the dashboard surfaces it. Mirrors
 * `LedgerEntry` from `neurogrim-cli::commands::publish_gate` but
 * omits `stdout_truncated` / `stderr_truncated` (the page doesn't
 * render full output; operators inspect the JSONL directly).
 */
export type PublishGateLedgerView = { run_id: string, gate_id: string, gate_type: string, mode: string, started_at: string, completed_at: string | null, status: string, blocking: boolean, operator: string | null, exit_code: number | null, error_detail: string | null, };
