// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishGateLedgerView } from "./PublishGateLedgerView";
import type { PublishGateView } from "./PublishGateView";

/**
 * Response body of `GET /api/brains/:brain_id/publish-gates` —
 * renders the manual-gate UI surface (`/brains/:id/publish-gates`).
 *
 * Combines the manifest (gate declarations) with the ledger (run
 * history) so the page can render "current state per gate" + a
 * recent-activity timeline in one fetch.
 *
 * Empty state: `manifest_present: false`, `gates: []`,
 * `recent_ledger: []`. Page renders an explainer pointing at
 * `neurogrim explain publish-gates`.
 *
 * Schema-corrupt state: `manifest_present: true`, `manifest_error:
 * Some(<schema-validation message>)`. Page surfaces a banner and
 * suggests `neurogrim doctor`.
 */
export type PublishGatesPageResponse = { 
/**
 * True when `<brain>/.claude/brain/publish-gates.yaml` exists
 * on disk (regardless of whether it parses).
 */
manifest_present: boolean, 
/**
 * Schema-validation or YAML-syntax error if the manifest is
 * present but malformed. None when the manifest is absent or
 * valid.
 */
manifest_error: string | null, 
/**
 * One entry per gate in the manifest, joined with the most
 * recent ledger entry for that gate. Order matches the
 * manifest's declared order (preserves operator intent).
 */
gates: Array<PublishGateView>, 
/**
 * Most recent N ledger entries, newest first. Capped at 50 in
 * v1 to keep the response payload tight; the page can offer a
 * "load more" affordance later if N=50 proves too small.
 */
recent_ledger: Array<PublishGateLedgerView>, };
