// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A gate as it appears in the dashboard's table — manifest fields
 * + the latest ledger entry's outcome (or `no_runs` for never-run
 * gates).
 */
export type PublishGateView = { id: string, gate_type: string, description: string, blocking: boolean, timeout_seconds: number | null, 
/**
 * Latest ledger entry's status, or `"no_runs"` if no ledger
 * entry exists yet for this gate. One of:
 * `passed | failed | pending | timed_out | deferred | error | no_runs`.
 */
current_status: string, 
/**
 * `started_at` of the latest ledger entry (RFC3339). None if
 * no ledger entry.
 */
last_run_at: string | null, 
/**
 * `run_id` of the latest ledger entry. Lets the page link
 * related ledger rows together.
 */
last_run_id: string | null, 
/**
 * Operator handle from the latest ledger entry, when present
 * (manual-gate `ack` or future `--operator` flag on automated).
 */
operator: string | null, };
