// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueueTopicStatsDto = { topic: string, message_count: number, size_bytes: bigint, 
/**
 * `produced_at` of the oldest message, RFC3339. None when empty.
 */
oldest: string | null, 
/**
 * `produced_at` of the newest message, RFC3339. None when empty.
 */
newest: string | null, };
