// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueMessageDto } from "./QueueMessageDto";

/**
 * Response body of `GET /api/brains/:brain_id/queues/:topic` — a
 * page of messages with the `next_offset` cursor for resume.
 */
export type QueueReadResponse = { topic: string, messages: Array<QueueMessageDto>, 
/**
 * Offset to pass as `since` on the next read to resume after
 * the last message in this page. Equals `since + messages.len()`.
 */
next_offset: bigint, };
