// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `POST /api/brains/:brain_id/queues/:topic` — the
 * freshly-produced message's identifiers. Body of the published
 * message is NOT echoed back; consumers fetch via the read endpoint
 * or subscribe to the SSE stream.
 */
export type QueuePublishResponse = { id: string, topic: string, produced_at: string, };
