// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One message in the wire format the dashboard returns. Mirrors
 * `neurogrim_core::queue::QueueMessage` but uses string typed fields
 * so the TS-side schema is stable across uuid / chrono crate version
 * drift.
 */
export type QueueMessageDto = { id: string, topic: string, payload: JsonValue, produced_at: string, priority: string, expires_at: string | null, };
