// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueTopicStatsDto } from "./QueueTopicStatsDto";

/**
 * Response body of `GET /api/brains/:brain_id/queues` — every
 * topic with a JSONL file on disk, plus per-topic stats.
 */
export type QueuesListResponse = { topics: Array<QueueTopicStatsDto>, };
