// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Request body of `POST /api/brains/:brain_id/queues/:topic`.
 * `payload` is required; `priority` and `expires_in_ms` are
 * optional. The bus generates `id` + `produced_at`.
 */
export type QueuePublishRequest = { payload: JsonValue, 
/**
 * "low" | "normal" | "high". Defaults to normal.
 */
priority: string | null, 
/**
 * Time-to-live in milliseconds; the bus computes
 * `expires_at = produced_at + expires_in_ms`. Default: never.
 */
expires_in_ms: bigint | null, };
