// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recommendation summary used in `OverviewResponse.top_recommendations`.
 */
export type RecommendationDto = { domain: string, gate: string, status: string, command: string, 
/**
 * Short human-readable rationale (from
 * `Recommendation::description`); may be empty if the source
 * recommendation didn't carry one.
 */
description: string, };
