// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body of `PUT /api/brains/:brain_id/registry`.
 */
export type RegistryUpdateRequest = { 
/**
 * ETag the client received on the GET. Server rejects with
 * 409 Conflict when the on-disk fingerprint differs.
 */
expected_etag: string, 
/**
 * Replacement registry JSON. Server validates via
 * `BrainRegistry::from_json` + `registry.validate()` before
 * writing.
 */
registry: Record<string, unknown>, };
