// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/brains/:brain_id/registry` — full
 * registry JSON + ETag fingerprint for conflict detection.
 *
 * **v1 scope:** the response is the raw registry JSON (as
 * `serde_json::Value`) plus an ETag derived from the file's bytes.
 * Curated forms on the frontend extract specific sections; the
 * schemars-driven full form generator + 3-way merge UI are
 * deferred until adopters need them.
 */
export type RegistryResponse = { brain_id: string, path: string, 
/**
 * SHA-256 of the file bytes at read-time, hex-encoded. The
 * frontend echoes this back on PUT; the server rejects with
 * 409 Conflict when the on-disk fingerprint differs (someone
 * else edited the file in the interim). v1 conflict mitigation;
 * 3-way merge UI is C-4 v2.
 */
etag: string, 
/**
 * Parsed registry JSON. Operator's curated forms extract
 * specific sections; the textarea-fallback editor renders the
 * raw object.
 */
registry: Record<string, unknown>, };
