// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body of `POST /api/brains/:brain_id/approvals/:action_id/resolve`.
 * Operator click flow: the dashboard server reads its own
 * `$NEUROGRIM_OPERATOR` env at startup and stamps it on the
 * resolution; buttons send only `{decision}`.
 */
export type ResolveApprovalRequest = { 
/**
 * `"approve"` | `"deny"`.
 */
decision: string, };
