// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolveApprovalResponse = { action_id: string, decision: string, operator: string | null, decided_at: string, };
