// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One snapshot from `<project>/.claude/brain/score-history.json`,
 * projected to a Logs-timeline shape: just the unified score plus
 * a delta against the prior snapshot. Per-domain detail lives in
 * the Domains pages — the Logs reader stays terse so a Brain
 * scored 50× per day doesn't drown the timeline.
 */
export type ScoreHistoryEntry = { 
/**
 * RFC3339 timestamp from the snapshot's `scored_at` field.
 */
scored_at: string, 
/**
 * Unified score on that snapshot (0-100, or null when the
 * Brain is fully advisory and the snapshot recorded `null`).
 */
score: number | null, 
/**
 * Delta vs. the previous snapshot in time-ordered sequence.
 * `None` for the oldest snapshot in the returned window
 * (no prior to diff against). `Some(0)` for unchanged scores.
 */
delta: number | null, };
