// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreHistoryEntry } from "./ScoreHistoryEntry";

/**
 * Response body of `GET /api/brains/:id/logs/score-history`.
 */
export type ScoreHistoryResponse = { 
/**
 * Resolved on-disk path. Helps operators correlate the timeline
 * with their score-history.json.
 */
history_path: string, 
/**
 * True when the file exists. False = empty timeline (the Brain
 * has never been scored).
 */
present: boolean, 
/**
 * Total snapshots parsed before the limit was applied. Surfaces
 * "history has 700 snapshots; we returned the most recent 50"
 * telemetry without forcing the operator to inspect the file.
 */
total_entries: number, 
/**
 * Entries newest-first, capped at the request's limit. The
 * `delta` field is computed against the chronologically-prior
 * snapshot (so the oldest entry in the returned slice has a
 * real delta when there's at least one snapshot beyond the
 * window; `None` when the slice covers the entire history).
 */
entries: Array<ScoreHistoryEntry>, };
