// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreHistoryEntry } from "./ScoreHistoryEntry";

/**
 * Response body of `GET /api/brains/:id/logs/score-history`.
 */
export type ScoreHistoryResponse = { 
/**
 * Resolved on-disk path. Points to the SQLite bus topic file
 * (`.claude/brain/queues/_neurogrim/score-snapshots.sqlite`)
 * for projects running the current binary, or to the legacy
 * `score-history.json` for projects that haven't scored yet
 * under the new binary.
 */
history_path: string, 
/**
 * True when the backing store exists. False = empty timeline
 * (the Brain has never been scored).
 */
present: boolean, 
/**
 * Total snapshots in the store before the limit was applied.
 * Surfaces "history has 700 snapshots; we returned the most
 * recent 50" telemetry without forcing the operator to inspect
 * the file.
 */
total_entries: number, 
/**
 * Entries newest-first, capped at the request's limit. The
 * `delta` field is computed against the chronologically-prior
 * snapshot (so the oldest entry in the returned slice has a
 * real delta when there's at least one snapshot beyond the
 * window; `None` when the slice covers the entire history).
 */
entries: Array<ScoreHistoryEntry>, };
