// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretListItem } from "./SecretListItem";

/**
 * Response body of `GET /api/brains/:id/secrets`.
 */
export type SecretsListResponse = { brain_id: string, 
/**
 * Path to the parsed manifest. Null when the file is absent
 * (operator hasn't authored one yet).
 */
manifest_path: string, manifest_present: boolean, 
/**
 * Ordered list (sorted by id). Includes secrets declared in
 * the manifest; secrets that exist in the SecretBackend
 * without a manifest entry are omitted from this list (they
 * would surface in `secrets-readiness` domain findings as
 * orphans — the dashboard presents the operator's declared
 * surface, not the backend's raw inventory).
 */
items: Array<SecretListItem>, };
