// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the secrets list endpoint response.
 */
export type SecretListItem = { 
/**
 * kebab-case secret id (the key in `secret-refs.yaml::secrets`).
 */
id: string, 
/**
 * Operator-facing description from the manifest.
 */
description: string | null, 
/**
 * Provider tag from the manifest.
 */
provider: string | null, 
/**
 * Rotation policy in days, if declared.
 */
rotation_days: number | null, 
/**
 * True iff a value is stored in the SecretBackend for this id.
 */
present: boolean, 
/**
 * RFC3339 of when the secret was last set/rotated. None if
 * not present.
 */
updated_at: string | null, 
/**
 * Backend that owns this secret (`os-native` /
 * `encrypted-file`). None if not present.
 */
backend: string | null, };
