// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * "Self" — what the Brain says about itself when describing the
 * federation. Mirrors the small subset of identity the operator
 * usually wants to confirm at a glance.
 */
export type SelfBrainDto = { 
/**
 * Display label for this Brain (registry.meta.description first
 * sentence; falls back to project_root basename).
 */
label: string, 
/**
 * Filesystem path to the project root.
 */
project_root: string, 
/**
 * Server version (CARGO_PKG_VERSION).
 */
version: string, };
