// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceLogEntry } from "./ServiceLogEntry";

/**
 * Response body of `GET /api/brains/:id/logs/services`.
 *
 * Backed by the `_neurogrim/services` SQLite bus topic since v4.4
 * (was `services.jsonl` previously). Falls back to the legacy JSONL
 * for projects that haven't yet emitted a service event under the
 * new binary.
 */
export type ServicesLogResponse = { log_path: string, present: boolean, total_entries: number, entries: Array<ServiceLogEntry>, };
