// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceSnapshot } from "./ServiceSnapshot";

/**
 * Wire-format response for `GET /api/brains/:id/services`. Lists
 * every service currently tracked by this dashboard.
 */
export type ServicesListResponse = { services: Array<ServiceSnapshot>, };
