// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-side snapshot of a tracked service. Serializable; safe to
 * send over the wire. Does NOT hold the `Child` (caller doesn't
 * need it for display purposes).
 */
export type ServiceSnapshot = { peer_name: string, pid: number, port: number, 
/**
 * RFC 3339 timestamp.
 */
started_at: string, log_path: string, };
