// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format error for the start/stop/probe endpoints. The
 * `code` field carries a stable string the frontend can switch
 * on (rather than parsing the human-readable `error`).
 */
export type ServiceErrorDto = { error: string, 
/**
 * One of: `mutations-disabled`, `peer-not-found`,
 * `already-running`, `not-running`, `port-conflict`,
 * `spawn-failed`, `internal`.
 */
code: string, };
