// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One on-disk row in `<project>/.claude/brain/services.jsonl`.
 *
 * Append-only ledger of terminal service-lifecycle events (started
 * / failed / stopped). The transient "starting" state is NOT logged
 * — only the resolved outcome lands on disk so the timeline reads
 * as a sequence of facts rather than wishes.
 *
 * Used by both:
 * - `crate::logs::read_services_log` (Logs page source)
 * - Future v5 work: dashboard-restart recovery (re-attach to
 *   already-running peers by reading the most-recent `started`
 *   that has no matching `stopped`).
 */
export type ServiceLogEntry = { 
/**
 * RFC3339 timestamp of the event.
 */
ts: string, 
/**
 * One of: `"started"` | `"failed"` | `"stopped"`.
 */
kind: string, peer_name: string, 
/**
 * PID of the spawned child. Present on `started` + `stopped`;
 * `None` on `failed` when the spawn itself didn't yield a PID
 * (port-conflict pre-spawn, etc.).
 */
pid: number | null, 
/**
 * Bound port. Present on `started`; `None` on `failed` /
 * `stopped` (where it would be redundant or unknown).
 */
port: number | null, 
/**
 * Failure reason for `failed` entries (port conflict, readiness
 * timeout, kill failure, etc.). `None` on success outcomes.
 */
reason: string | null, };
