// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceLogEntry } from "./ServiceLogEntry";

/**
 * Response body of `GET /api/brains/:id/logs/services`.
 *
 * Mirrors the on-disk JSONL ledger shape but typed + projected for
 * the Logs page. The ledger is append-only; we re-read on each
 * request and return the most-recent N entries newest-first. A
 * future v5 may add streaming-read for very long histories, but
 * services.jsonl grows much more slowly than invocation-ledger
 * (operators don't restart peers constantly), so the simple read
 * is sufficient.
 */
export type ServicesLogResponse = { log_path: string, present: boolean, total_entries: number, entries: Array<ServiceLogEntry>, };
