// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `POST /api/brains/:id/secrets/:secret_id`
 * (success path).
 */
export type SetSecretResponse = { brain_id: string, secret_id: string, 
/**
 * RFC3339 of when the write completed. Useful for the UI to
 * flash "Saved at <ts>" without re-fetching the whole list.
 */
updated_at: string, };
