// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body of `POST /api/brains/:id/secrets/:secret_id`.
 * Carries the plaintext value; the server consumes it into a
 * zeroizing `SecretValue` before any response is built.
 */
export type SetSecretRequest = { 
/**
 * Plaintext value. Server moves this into a `SecretValue`
 * immediately + drops the raw String. Not echoed in the
 * response.
 */
value: string, };
