// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row in the Skills table.
 */
export type SkillDto = { 
/**
 * Skill id — kebab-case folder/file name. Matches the `name`
 * field in invocation-ledger entries (Claude Code's per-skill
 * surface name).
 */
name: string, 
/**
 * Filesystem path relative to project root, e.g.
 * `.claude/skills/rubber-duck/SKILL.md` or `.claude/skills/foo.md`.
 */
path: string, 
/**
 * One of "plugin" (folder + SKILL.md) | "legacy" (single .md
 * file directly under .claude/skills/).
 */
format: string, 
/**
 * First-paragraph description. Pulled from YAML frontmatter
 * (`description:`) for plugin skills, from the lead paragraph
 * for legacy. May be empty if the file lacks both.
 */
description: string, 
/**
 * Most-recent invocation timestamp from the ledger (RFC 3339).
 * None when never invoked or no ledger.
 */
last_invoked_at: string | null, 
/**
 * Total invocation count from the ledger (all time, not windowed).
 * Sum of hard + soft.
 */
invocation_count: number, 
/**
 * Invocations in the alive_window. Used to drive the
 * alive/dead/new classification and shown in the table for
 * at-a-glance freshness. Sum of hard + soft.
 */
recent_invocation_count: number, 
/**
 * "Hard" invocations: explicit `Skill` tool calls (slash
 * commands or `Skill(name=...)`). All-time.
 */
hard_invocations: number, 
/**
 * "Soft" invocations: agent reads of the SKILL.md file via
 * the Read tool. All-time. Captures the more common usage
 * pattern where an agent follows skill guidance without
 * going through the Skill tool. Schema-1 ledger entries
 * (pre-soft tracking) are counted as hard.
 */
soft_invocations: number, 
/**
 * Hard invocations within the alive_window.
 */
recent_hard_invocations: number, 
/**
 * Soft invocations within the alive_window.
 */
recent_soft_invocations: number, 
/**
 * One of "alive" | "dead" | "new" | "no-ledger".
 * - alive: at least one invocation in the alive_window
 * - dead: invocations exist but none in the alive_window
 * - new: never invoked
 * - no-ledger: ledger file is missing entirely (PostToolUse
 *   hook hasn't been wired up)
 */
hygiene_status: string, };
