// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillDto } from "./SkillDto";

/**
 * Response body of `GET /api/skills` — inventory + hygiene of every
 * skill the Brain can route to under `.claude/skills/`.
 *
 * The dashboard renders this as a filterable table grouped by
 * hygiene status (alive / dead / new), with click-to-expand for the
 * frontmatter description.
 */
export type SkillsResponse = { skills: Array<SkillDto>, 
/**
 * True when `.claude/brain/invocation-ledger.jsonl` exists. When
 * false, all skills will have hygiene_status = "no-ledger" — the
 * page surfaces a banner explaining that the PostToolUse hook
 * hasn't been wired up yet.
 */
ledger_present: boolean, 
/**
 * Total skill-typed entries in the ledger (any age). Useful as a
 * "ledger isn't empty, just has no recent activity" sanity signal.
 */
total_invocations: number, 
/**
 * Window (in days) used to classify alive/dead. Surfaced so the
 * page can label the legend ("alive = invoked in last 30 days").
 */
alive_window_days: number, };
