// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format response for `POST /api/brains/:id/peers/:peer/start`.
 */
export type StartPeerResponse = { 
/**
 * "starting" — the spawn handler returns immediately and the
 * readiness watcher emits SSE events as the state evolves.
 */
state: string, peer_name: string, pid: number, port: number, };
