// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format response for `POST /api/brains/:id/peers/:peer/stop`.
 */
export type StopPeerResponse = { 
/**
 * "stopped" — child killed, registry entry removed.
 */
state: string, peer_name: string, };
