// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `GET /api/tls-status` (v4.2 S14-S-4.5 v3).
 *
 * Lets the Secrets page determine whether HTTPS is available +
 * what fingerprint to pin in localStorage for TOFU verification.
 * This endpoint serves on BOTH the HTTP and HTTPS listeners — the
 * values are public (cert fingerprint is by definition public,
 * HTTPS port is loopback-only) so there's no harm in exposing
 * them over either listener.
 */
export type TlsStatusResponse = { 
/**
 * True when the dashboard has both cert + key on disk and
 * the HTTPS listener is bound. The frontend uses this to
 * decide whether to render the "switch to HTTPS" banner on
 * secret-management pages.
 */
https_available: boolean, 
/**
 * HTTPS listener port. None when `https_available` is false.
 * Conventionally the HTTP port + 1.
 */
https_port: number | null, 
/**
 * SHA-256 fingerprint of the cert (lowercase hex, no
 * separators). Frontend pins this in localStorage on first
 * visit; subsequent visits compare to detect rotation or
 * MITM. None when no cert file is on disk.
 */
fingerprint_sha256: string | null, };
