// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One widget on the dashboard.
 */
export type WidgetSpec = { 
/**
 * Stable id within the layout — used by the frontend as a
 * React key and (in the next-pass edit mode) as a target for
 * move/remove operations.
 */
id: string, 
/**
 * Widget kind. Matches a component name in the frontend's
 * widget registry (`components/widgets/index.ts`). Stringly-typed
 * at the wire so unknown widget types render gracefully (the
 * frontend shows a "[unknown widget]" placeholder rather than
 * crashing the page).
 */
widget_type: string, 
/**
 * One of "full" | "half" | "third" | "quarter". Maps to a
 * fractional row width — full=12/12, half=6/12, third=4/12,
 * quarter=3/12. Widgets flow left-to-right; if a widget would
 * overflow the current row, it starts a new row.
 */
size: string, 
/**
 * Optional title override for the widget header. None →
 * widget uses its own default title.
 */
title: string | null, 
/**
 * Widget-specific configuration (JSON object). Each widget
 * type interprets this differently; e.g., `domain-card` uses
 * `{ "domain": "child-neurogrim" }`, `markdown-note` uses
 * `{ "content": "..." }`.
 *
 * Typed as `Record<string, unknown>` in the generated TS
 * bindings — ts-rs doesn't have an automatic mapping for
 * `serde_json::Value`. Each frontend widget component is
 * responsible for narrowing its slice of the config object.
 */
config: Record<string, unknown>, };
