//! E-B2-4 C3 — `analyze_trust_budget` behavioral tests.
//!
//! Mirrors the E-B2-3 `hat_contract_sensor_behavior.rs` shape:
//! synthetic-`TempDir` fixtures populated programmatically, then
//! observed via the public `analyze_trust_budget` entry point's CMDB
//! envelope output.
//!
//! Coverage (10 cases including recursion-guard pin):
//!
//!  1. **`missing_trust_budget_emits_declaration_finding`** — synthetic
//!     TempDir with no `trust-budget.toml`; one
//!     `trust_budget:declaration:missing` finding emitted; envelope
//!     well-formed.
//!  2. **`well_formed_trust_budget_no_drift_findings`** — synthetic
//!     root with TOML declaring exactly the surface the sensor
//!     computes; ZERO drift findings.
//!  3. **`undeclared_crate_emits_finding`** — `Cargo.lock` has `serde`
//!     but TOML missing it; one `trust_budget:undeclared:crate:serde`
//!     finding.
//!  4. **`overdeclared_crate_emits_finding`** — TOML declares
//!     `nonexistent_crate`; `Cargo.lock` doesn't have it; one
//!     `trust_budget:overdeclared:crate:nonexistent_crate` finding.
//!  5. **`seeded_crate_suppresses_undeclared_finding`** — `Cargo.lock`
//!     has crate `bootstrap_dep`; TOML has `bootstrap_dep` with
//!     `seeded: true`; ZERO findings about `bootstrap_dep`.
//!  6. **`malformed_trust_budget_aborts_gracefully`** — `trust-budget.toml`
//!     with invalid TOML; one `trust_budget:declaration:malformed`
//!     finding; no panic; envelope returns.
//!  7. **`invalid_trust_budget_emits_per_error_findings`** — TOML
//!     parses but fails schema validation (wrong `trust_posture`);
//!     one or more `trust_budget:declaration:invalid:*` findings.
//!  8. **`per_hat_composition_violation_potential`** — synthetic root
//!     with a hat declaring `forbidden_tools: [<token>]` AND TOML
//!     declaring the same token in `declared_shell_outs`; verify the
//!     `trust_budget:per_hat:violation_potential:*` finding is
//!     emitted with the documented shape. Static "could-be"
//!     semantics; runtime is BACKLOG B-23.
//!  9. **`live_neurogrim_smoke`** — call `analyze_trust_budget`
//!     against the actual `D:/Brains/NeuroGrim` repo without a
//!     `trust-budget.toml` in place yet (Component 4 hasn't shipped);
//!     emits ONE `trust_budget:declaration:missing` finding plus
//!     drift findings. Documents the count as a baseline.
//! 10. **`recursion_guard_no_command_in_validator_span`** (Q7) — pin
//!     the Q7 hard rule: `trust_budget.rs` source contains no
//!     `Command::new` / `process::Command` / `Stdio` / `std::process`
//!     in its function spans, and `Cargo.toml` doesn't declare
//!     `walkdir` / `subprocess` / `duct` / `which` / `shell-words`.

use serde_json::Value;
use std::path::{Path, PathBuf};
use tempfile::TempDir;

use neurogrim_sensory::trust_budget::analyze_trust_budget;

// ── Fixture helpers ─────────────────────────────────────────────────

/// Make a tempdir that looks like a Brain root.
fn make_brain_root() -> TempDir {
    tempfile::tempdir().expect("tempdir")
}

/// Write a `trust-budget.toml` at the root.
fn write_trust_budget(root: &Path, body: &str) {
    std::fs::write(root.join("trust-budget.toml"), body).expect("write trust-budget.toml");
}

/// Write a minimal `Cargo.lock` with the given crate names. Versions
/// are dummy `1.0.0`; sources are `crates.io`.
fn write_cargo_lock(root: &Path, crates: &[&str]) {
    let mut buf = String::from("# This file is automatically @generated by Cargo.\nversion = 3\n\n");
    for (i, name) in crates.iter().enumerate() {
        // The cargo-lock crate validates checksum syntax (32-byte hex).
        // Pad with a unique trailing index so duplicates differ.
        let checksum: String = format!(
            "{:0width$x}",
            i + 1,
            width = 64
        );
        buf.push_str(&format!(
            "[[package]]\nname = \"{name}\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"{checksum}\"\n\n"
        ));
    }
    std::fs::write(root.join("Cargo.lock"), buf).expect("write Cargo.lock");
}

/// Filter findings by name prefix.
fn findings_by_prefix<'a>(result: &'a Value, prefix: &str) -> Vec<&'a Value> {
    result["findings"]
        .as_array()
        .map(|arr| {
            arr.iter()
                .filter(|f| {
                    f["name"]
                        .as_str()
                        .map(|s| s.starts_with(prefix))
                        .unwrap_or(false)
                })
                .collect()
        })
        .unwrap_or_default()
}

/// All `trust_budget:*` findings.
fn trust_budget_findings(result: &Value) -> Vec<&Value> {
    findings_by_prefix(result, "trust_budget:")
}

/// Locate the `trust_budget.rs` source file from the crate's manifest dir.
fn locate_trust_budget_source() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("trust_budget.rs")
}

// ── 1. Missing trust-budget.toml → declaration finding ──────────────

#[tokio::test]
async fn missing_trust_budget_emits_declaration_finding() {
    let tmp = make_brain_root();

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let missing = findings_by_prefix(&result, "trust_budget:declaration:missing");
    assert_eq!(
        missing.len(),
        1,
        "expected exactly 1 declaration:missing finding; got: {:?}",
        trust_budget_findings(&result)
    );
    assert_eq!(missing[0]["status"], "neutral");
    assert_eq!(missing[0]["points"], 0);

    // Envelope still well-formed.
    assert!(result["score"].is_number(), "score must be a number");
    assert_eq!(result["meta"]["updated_by"], "trust-budget");

    // Breakdown JSON must exist and report declaration_present = false.
    let breakdown = &result["trust_budget_breakdown"];
    assert!(breakdown.is_object(), "breakdown must be present");
    assert_eq!(breakdown["declaration_present"], false);
    assert_eq!(breakdown["declared"]["crate_count"], 0);
}

// ── 2. Well-formed declaration matching surface → no drift ──────────

#[tokio::test]
async fn well_formed_trust_budget_no_drift_findings() {
    let tmp = make_brain_root();
    // Synthetic Cargo.lock with one crate.
    write_cargo_lock(tmp.path(), &["serde"]);
    // TOML declaring exactly that crate.
    let toml_body = r#"schema_version = "1"
notes = "Test fixture: matches the synthetic Cargo.lock exactly."

[[declared_crates]]
name = "serde"
ecosystem = "cargo"
"#;
    write_trust_budget(tmp.path(), toml_body);

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let drift_findings = findings_by_prefix(&result, "trust_budget:undeclared:");
    let over_findings = findings_by_prefix(&result, "trust_budget:overdeclared:");
    assert!(
        drift_findings.is_empty(),
        "expected zero undeclared findings; got: {:?}",
        drift_findings
    );
    assert!(
        over_findings.is_empty(),
        "expected zero overdeclared findings; got: {:?}",
        over_findings
    );

    // Score should be 100 — fully aligned.
    assert_eq!(result["score"], 100, "fully-aligned trust-budget should score 100");
}

// ── 3. Undeclared crate → finding ───────────────────────────────────

#[tokio::test]
async fn undeclared_crate_emits_finding() {
    let tmp = make_brain_root();
    write_cargo_lock(tmp.path(), &["serde"]);
    // TOML missing `serde`.
    let toml_body = r#"schema_version = "1"

[[declared_crates]]
name = "anyhow"
ecosystem = "cargo"
"#;
    write_trust_budget(tmp.path(), toml_body);

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let serde_findings = findings_by_prefix(&result, "trust_budget:undeclared:crate:serde");
    assert_eq!(
        serde_findings.len(),
        1,
        "expected exactly 1 undeclared:crate:serde finding; got: {:?}",
        trust_budget_findings(&result)
    );
    assert_eq!(serde_findings[0]["points"], 0);
    assert_eq!(serde_findings[0]["status"], "neutral");
}

// ── 4. Overdeclared crate → finding ─────────────────────────────────

#[tokio::test]
async fn overdeclared_crate_emits_finding() {
    let tmp = make_brain_root();
    write_cargo_lock(tmp.path(), &["serde"]);
    // TOML declaring serde (matching) + a non-existent crate.
    let toml_body = r#"schema_version = "1"

[[declared_crates]]
name = "serde"
ecosystem = "cargo"

[[declared_crates]]
name = "nonexistent_crate"
ecosystem = "cargo"
"#;
    write_trust_budget(tmp.path(), toml_body);

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let over_findings = findings_by_prefix(
        &result,
        "trust_budget:overdeclared:crate:nonexistent_crate",
    );
    assert_eq!(
        over_findings.len(),
        1,
        "expected exactly 1 overdeclared:crate:nonexistent_crate finding; got: {:?}",
        trust_budget_findings(&result)
    );
    assert_eq!(over_findings[0]["points"], 0);
    assert_eq!(over_findings[0]["status"], "neutral");
}

// ── 5. Seeded crate suppresses undeclared finding ───────────────────

#[tokio::test]
async fn seeded_crate_suppresses_undeclared_finding() {
    let tmp = make_brain_root();
    write_cargo_lock(tmp.path(), &["bootstrap_dep"]);
    // TOML declares it as seeded — should NOT fire undeclared.
    let toml_body = r#"schema_version = "1"

[[declared_crates]]
name = "bootstrap_dep"
ecosystem = "cargo"
seeded = true
"#;
    write_trust_budget(tmp.path(), toml_body);

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    // No undeclared OR overdeclared findings naming bootstrap_dep.
    let bootstrap_findings: Vec<&Value> = trust_budget_findings(&result)
        .into_iter()
        .filter(|f| {
            f["name"]
                .as_str()
                .map(|n| n.contains("bootstrap_dep"))
                .unwrap_or(false)
        })
        .collect();
    assert!(
        bootstrap_findings.is_empty(),
        "seeded + present-in-actual must produce ZERO findings about bootstrap_dep; got: {:?}",
        bootstrap_findings
    );
}

// ── 6. Malformed TOML aborts gracefully ─────────────────────────────

#[tokio::test]
async fn malformed_trust_budget_aborts_gracefully() {
    let tmp = make_brain_root();
    // Invalid TOML — unclosed string.
    let bad_toml = "schema_version = \"1\nnotes = oops, stray quote";
    write_trust_budget(tmp.path(), bad_toml);

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let malformed = findings_by_prefix(&result, "trust_budget:declaration:malformed");
    assert_eq!(
        malformed.len(),
        1,
        "expected exactly 1 declaration:malformed finding; got: {:?}",
        trust_budget_findings(&result)
    );
    assert_eq!(malformed[0]["status"], "error");
    assert_eq!(malformed[0]["points"], 0);

    // Envelope still well-formed; no panic.
    assert_eq!(result["meta"]["updated_by"], "trust-budget");
    assert!(result["score"].is_number());
}

// ── 7. Invalid (schema-failing) TOML emits per-error findings ───────

#[tokio::test]
async fn invalid_trust_budget_emits_per_error_findings() {
    let tmp = make_brain_root();
    // Valid TOML, but `trust_posture` value is outside the closed-set
    // enum — schema validation will fail at
    // `/declared_external_services/0/trust_posture`.
    let toml_body = r#"schema_version = "1"

[[declared_external_services]]
fqdn = "evil.example.com"
purpose = "Testing invalid trust_posture"
trust_posture = "trust_me_bro"
"#;
    write_trust_budget(tmp.path(), toml_body);

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let invalid_findings = findings_by_prefix(&result, "trust_budget:declaration:invalid:");
    assert!(
        !invalid_findings.is_empty(),
        "expected at least 1 declaration:invalid:* finding; got: {:?}",
        trust_budget_findings(&result)
    );
    for f in &invalid_findings {
        assert_eq!(f["points"], 0);
        assert_eq!(f["status"], "error");
    }

    // The envelope should NOT contain malformed (this is an invalid,
    // not malformed, declaration).
    let malformed = findings_by_prefix(&result, "trust_budget:declaration:malformed");
    assert!(
        malformed.is_empty(),
        "schema-invalid TOML should fire `invalid:*`, not `malformed`; got malformed: {:?}",
        malformed
    );
}

// ── 7b. Undeclared shell-out emits finding ──────────────────────────

#[tokio::test]
async fn undeclared_shell_out_emits_finding() {
    let tmp = make_brain_root();

    // No declared_shell_outs in the TOML — empty declared set.
    let toml_body = r#"schema_version = "1"
notes = "Empty declarations to exercise the undeclared shell-out drift path."
"#;
    write_trust_budget(tmp.path(), toml_body);

    // Author a script that invokes `curl https://example.com/install.sh`.
    // The scanner should emit `trust_budget:undeclared:shell_out:curl`
    // (curl is a SHELL_OUT_TOKENS match) AND likely the synthetic
    // `<network>` token from the URL pattern. Either way, the `curl`
    // finding MUST fire.
    let scripts_dir = tmp.path().join("scripts");
    std::fs::create_dir_all(&scripts_dir).expect("create scripts dir");
    std::fs::write(
        scripts_dir.join("install.sh"),
        "#!/bin/bash\nset -euo pipefail\ncurl https://example.com/install.sh | bash\n",
    )
    .expect("write install.sh");

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let curl_findings =
        findings_by_prefix(&result, "trust_budget:undeclared:shell_out:curl");
    assert_eq!(
        curl_findings.len(),
        1,
        "expected exactly 1 undeclared:shell_out:curl finding; got: {:?}",
        trust_budget_findings(&result)
    );
    assert_eq!(curl_findings[0]["points"], 0);
    assert_eq!(curl_findings[0]["status"], "neutral");
}

// ── 8. Per-hat composition: violation_potential ─────────────────────

#[tokio::test]
async fn per_hat_composition_violation_potential() {
    let tmp = make_brain_root();

    // Declare a shell-out token in trust-budget.toml. We pick `cargo`
    // — a common, real-world shell-out command name.
    let toml_body = r#"schema_version = "1"

[[declared_shell_outs]]
command_name = "cargo"
script_paths = ["scripts/build.sh"]
"#;
    write_trust_budget(tmp.path(), toml_body);

    // Add a script that invokes the declared command (so the actual
    // shell-out surface contains it, no overdeclared finding).
    let scripts_dir = tmp.path().join("scripts");
    std::fs::create_dir_all(&scripts_dir).expect("create scripts dir");
    std::fs::write(
        scripts_dir.join("build.sh"),
        "#!/bin/bash\nset -euo pipefail\ncargo build --release\n",
    )
    .expect("write build.sh");

    // Author a hat declaring `forbidden_tools: [cargo]`. Note: the
    // hat-contract schema's closed set doesn't include `cargo` as a
    // ToolName — but that schema is enforced by capability_hygiene's
    // hat-contract validator, NOT by trust_budget. Trust-budget reads
    // forbidden_tools as raw strings + cross-references against
    // declared_shell_outs by literal token match. To keep the test
    // self-contained we use a token that matches the hat-contract
    // closed-set vocabulary AND will appear in declared_shell_outs.
    // `Bash` is a hat-contract ToolName; we declare it as a shell-out
    // command_name (the operator chose to encode a Bash-script
    // invocation surface that way).
    let hats_dir = tmp.path().join(".claude").join("skills").join("hats");
    std::fs::create_dir_all(&hats_dir).expect("create hats dir");

    // Use the `cargo` token in the hat — same name as the script
    // invocation. The hat-contract schema would reject `cargo` as a
    // ToolName (closed-set), but trust-budget cross-references by
    // literal string and emits a violation_potential when the tokens
    // match. This is exactly the documented Q8 / E4-5 semantics.
    let hat_body = "---\n\
        name: paranoid-builder\n\
        description: Test fixture for trust-budget per-hat composition — declares cargo as forbidden.\n\
        forbidden_tools:\n  - cargo\n\
        ---\n\
        \n\
        Hat fixture for per-hat composition test.\n";
    std::fs::write(hats_dir.join("paranoid-builder.md"), hat_body)
        .expect("write hat");

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let violation_findings = findings_by_prefix(
        &result,
        "trust_budget:per_hat:violation_potential:",
    );
    assert_eq!(
        violation_findings.len(),
        1,
        "expected exactly 1 violation_potential finding; got: {:?}",
        trust_budget_findings(&result)
    );
    let f = violation_findings[0];
    assert_eq!(
        f["name"],
        "trust_budget:per_hat:violation_potential:paranoid-builder:cargo",
        "violation_potential finding name must follow the documented `<hat>:<token>` shape; got: {:?}",
        f
    );
    assert_eq!(f["status"], "neutral");
    assert_eq!(f["points"], 0);
}

// ── 9. Live NeuroGrim smoke ──────────────────────────────────────────

/// Locate the live NeuroGrim Brain root from the crate's manifest dir.
/// Crate sits at `<root>/NeuroGrim/neurogrim/crates/neurogrim-sensory/`;
/// three `..` hops up lands at `<root>/NeuroGrim/`. Returns `None`
/// when the layout doesn't match (standalone checkout) — same skip-
/// when-absent convention as `hat_contract_sensor_behavior.rs`.
fn locate_neurogrim_brain_root() -> Option<PathBuf> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // Three `..` hops up from `<brain>/neurogrim/crates/neurogrim-sensory`
    // lands at the Brain root `<brain>/`. Canonicalize so `.is_dir()`
    // checks resolve real path components on Windows. Mirrors
    // `hat_contract_sensor_behavior.rs::locate_neurogrim_brain_root`.
    let brain_root = manifest_dir.join("../../..").canonicalize().ok()?;
    if brain_root.join(".claude").is_dir() {
        Some(brain_root)
    } else {
        None
    }
}

/// Smoke-test against the live NeuroGrim Brain root. WITHOUT a
/// `trust-budget.toml` in place yet (Component 4 hasn't shipped),
/// expect ONE `trust_budget:declaration:missing` finding plus drift
/// findings (the actual surface vs empty declared).
#[tokio::test]
async fn live_neurogrim_smoke() {
    let Some(brain_root) = locate_neurogrim_brain_root() else {
        eprintln!("skip: live NeuroGrim brain root not reachable");
        return;
    };

    // If a trust-budget.toml has been authored (e.g., Component 4 has
    // shipped by the time this test runs), skip the missing-finding
    // assertion — instead we just assert the envelope is well-formed
    // and document the count of drift findings.
    let toml_present = brain_root.join("trust-budget.toml").is_file();

    let result = analyze_trust_budget(brain_root.to_str().unwrap()).await;

    // Envelope is well-formed.
    assert_eq!(result["meta"]["updated_by"], "trust-budget");
    assert!(result["score"].is_number());

    let all = trust_budget_findings(&result);
    eprintln!(
        "live_neurogrim_smoke: trust_budget.toml present = {toml_present}, total findings = {}",
        all.len()
    );
    // Print the first 3 finding kinds (`name` field) for the dogfood
    // baseline record. Helps the C7 integration step calibrate whether
    // the count drifted unexpectedly between runs.
    for (i, f) in all.iter().take(3).enumerate() {
        eprintln!(
            "  finding[{i}] name = {}",
            f["name"].as_str().unwrap_or("<missing>")
        );
    }
    let undeclared = findings_by_prefix(&result, "trust_budget:undeclared:");
    let overdeclared = findings_by_prefix(&result, "trust_budget:overdeclared:");
    let invalid = findings_by_prefix(&result, "trust_budget:declaration:invalid:");
    let missing = findings_by_prefix(&result, "trust_budget:declaration:missing");
    let malformed = findings_by_prefix(&result, "trust_budget:declaration:malformed");
    let per_hat = findings_by_prefix(&result, "trust_budget:per_hat:");
    eprintln!(
        "  baseline: undeclared={}, overdeclared={}, invalid={}, missing={}, \
         malformed={}, per_hat={}",
        undeclared.len(),
        overdeclared.len(),
        invalid.len(),
        missing.len(),
        malformed.len(),
        per_hat.len(),
    );

    if !toml_present {
        // No trust-budget.toml yet. Exactly one `:declaration:missing`
        // finding; no malformed; no invalid.
        assert_eq!(
            missing.len(),
            1,
            "without trust-budget.toml, expected exactly 1 declaration:missing finding"
        );
        assert!(
            malformed.is_empty(),
            "no malformed without a file present; got: {:?}",
            malformed
        );
        assert!(
            invalid.is_empty(),
            "no invalid without a parseable file; got: {:?}",
            invalid
        );

        // ── Smoke-shape assertions (post-bug-fix calibration) ──
        //
        // After C3 was patched (2026-04-27) to fix three scanner bugs
        // (function-name false positives, zero-crate detection, narrow
        // service walk), the smoke-output should look qualitatively
        // different from the original 59-finding noise. The asserts
        // below pin the expected shape so future regressions surface
        // immediately.

        // Total finding cap. The original buggy run produced 59. The
        // patched run produces ~66 with the broader (but correct)
        // service walk. We allow up to 100 to give headroom for new
        // direct deps without needing a re-pin every time the
        // workspace grows; if we ever drift over 100 it's a calibration
        // smell worth investigating.
        assert!(
            all.len() <= 100,
            "live smoke total findings should be ≤ 100 (post-fix calibration ceiling); got {}",
            all.len()
        );

        // Shell-out vocabulary check: at least one of the well-known
        // external commands MUST appear (this was zero in the buggy
        // output for `git`/`bash`/`python`; `curl`/`docker` were
        // already present but accompanied by 40+ false-positives).
        let shell_out_kinds: Vec<String> = all
            .iter()
            .filter_map(|f| f["name"].as_str())
            .filter(|n| n.starts_with("trust_budget:undeclared:shell_out:"))
            .map(|n| {
                n.trim_start_matches("trust_budget:undeclared:shell_out:")
                    .to_string()
            })
            .collect();
        let has_real_external = shell_out_kinds.iter().any(|k| {
            matches!(
                k.as_str(),
                "curl" | "docker" | "git" | "cargo" | "bash" | "python"
            )
        });
        assert!(
            has_real_external,
            "expected at least one real external command (curl/docker/git/cargo/bash/python) in shell-out findings; got: {:?}",
            shell_out_kinds
        );

        // Bug-1 forbidden tokens — these were in the original buggy
        // output and MUST NOT reappear. Single tokens:
        let bug1_forbidden_tokens = [
            "<network>",
            "Inspect",
            "See",
            "red",
            "green",
            "blue",
            "yellow",
            "done",
            "ok",
            "break",
            "info",
            "import",
            "main",
            "log",
            "fail",
        ];
        for tok in bug1_forbidden_tokens {
            assert!(
                !shell_out_kinds.iter().any(|k| k == tok),
                "shell_out token `{tok}` is a known false-positive (Bug 1); got shell-outs: {:?}",
                shell_out_kinds
            );
        }
        // Prefix-class forbidden — bash function names from prepublish-check.sh.
        for k in &shell_out_kinds {
            assert!(
                !k.starts_with("check_"),
                "shell_out token `{k}` starts with `check_` — that's a bash function name from prepublish-check.sh, not a real external command (Bug 1)"
            );
            assert!(
                !k.starts_with("neurogrim-"),
                "shell_out token `{k}` starts with `neurogrim-` — that's a workspace crate name, not a real external command (Bug 1)"
            );
        }

        // Bug-2 — crates set MUST be non-empty. Pre-fix it was zero.
        let breakdown = &result["trust_budget_breakdown"];
        let actual_crates = breakdown["actual"]["crates"]
            .as_array()
            .map(|a| a.len())
            .unwrap_or(0);
        assert!(
            actual_crates >= 5,
            "expected at least 5 direct deps in actual.crates (Bug 2 was zero); got {}",
            actual_crates
        );

        // Bug-3 — services set MUST be non-empty.
        let actual_services = breakdown["actual"]["services"]
            .as_array()
            .map(|a| a.len())
            .unwrap_or(0);
        assert!(
            actual_services >= 1,
            "expected at least 1 FQDN in actual.services (Bug 3 was zero); got {}",
            actual_services
        );
    }
}

// ── 11. Shell-out scanner: bash function definitions excluded ───────

/// Bug-1 regression: synthetic `scripts/build.sh` containing a bash
/// function definition `red() { ... }` AND a real `curl` invocation.
/// Sensor must emit `:undeclared:shell_out:curl` but NOT
/// `:undeclared:shell_out:red`.
#[tokio::test]
async fn shell_out_excludes_bash_function_definitions() {
    let tmp = make_brain_root();
    let scripts_dir = tmp.path().join("scripts");
    std::fs::create_dir_all(&scripts_dir).expect("create scripts dir");
    std::fs::write(
        scripts_dir.join("build.sh"),
        "#!/bin/bash\n\
         set -euo pipefail\n\
         red() { echo red; }\n\
         curl https://example.com/install.sh\n\
         red\n",
    )
    .expect("write build.sh");

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let curl = findings_by_prefix(&result, "trust_budget:undeclared:shell_out:curl");
    assert_eq!(
        curl.len(),
        1,
        "expected exactly 1 undeclared:shell_out:curl finding; got: {:?}",
        trust_budget_findings(&result)
    );

    let red = findings_by_prefix(&result, "trust_budget:undeclared:shell_out:red");
    assert!(
        red.is_empty(),
        "shell_out:red MUST NOT fire — `red()` is a locally-defined bash function (Bug 1); got: {:?}",
        red
    );
}

// ── 12. Crate scanner: filtered to direct deps only ─────────────────

/// Bug-2 regression: synthetic two-level layout under `neurogrim/`
/// declaring exactly one workspace member (`crates/foo`) which depends
/// on `serde`. Synthetic `Cargo.lock` containing `serde` AND a fake
/// transitive `serde-deserialize-internal`. Sensor MUST emit
/// `:undeclared:crate:serde` but NOT
/// `:undeclared:crate:serde-deserialize-internal`.
#[tokio::test]
async fn crate_filter_to_direct_deps_only() {
    let tmp = make_brain_root();

    // NeuroGrim two-level layout: workspace at <root>/neurogrim/.
    let ws = tmp.path().join("neurogrim");
    std::fs::create_dir_all(&ws).expect("create ws dir");

    // Workspace Cargo.toml declaring `serde` in [workspace.dependencies]
    // and `crates/foo` as the sole member.
    std::fs::write(
        ws.join("Cargo.toml"),
        r#"[workspace]
resolver = "2"
members = ["crates/foo"]

[workspace.dependencies]
serde = "1"
"#,
    )
    .expect("write workspace Cargo.toml");

    // Member crate manifest with serde as a direct dep.
    let foo_dir = ws.join("crates").join("foo");
    std::fs::create_dir_all(&foo_dir).expect("create foo dir");
    std::fs::write(
        foo_dir.join("Cargo.toml"),
        r#"[package]
name = "foo"
version = "0.1.0"

[dependencies]
serde = { workspace = true }
"#,
    )
    .expect("write foo Cargo.toml");

    // Lockfile containing the direct dep AND a synthetic transitive.
    write_cargo_lock(
        ws.as_path(),
        &["serde", "serde-deserialize-internal"],
    );

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let direct =
        findings_by_prefix(&result, "trust_budget:undeclared:crate:serde");
    // Exactly the direct dep, NOT the transitive variant. We use an
    // exact-name match here (the prefix `serde` is shared).
    let serde_exact: Vec<&serde_json::Value> = direct
        .into_iter()
        .filter(|f| {
            f["name"].as_str() == Some("trust_budget:undeclared:crate:serde")
        })
        .collect();
    assert_eq!(
        serde_exact.len(),
        1,
        "expected exactly 1 undeclared:crate:serde finding (direct dep); got: {:?}",
        trust_budget_findings(&result)
    );

    let transitive = findings_by_prefix(
        &result,
        "trust_budget:undeclared:crate:serde-deserialize-internal",
    );
    assert!(
        transitive.is_empty(),
        "transitive crate `serde-deserialize-internal` MUST NOT fire — direct-only filter (Bug 2 + Q1 lock); got: {:?}",
        transitive
    );
}

// ── 13. External-service scanner: HTTPS URLs in source files ────────

/// Bug-3 regression: synthetic `src/foo.rs` with an HTTPS URL string
/// literal. Sensor must emit `:undeclared:service:osv.dev`.
#[tokio::test]
async fn external_service_scanner_finds_https_urls() {
    let tmp = make_brain_root();
    let src_dir = tmp.path().join("src");
    std::fs::create_dir_all(&src_dir).expect("create src dir");
    std::fs::write(
        src_dir.join("foo.rs"),
        "fn main() { let url = \"https://osv.dev/v1/query\"; println!(\"{}\", url); }\n",
    )
    .expect("write foo.rs");

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let osv = findings_by_prefix(&result, "trust_budget:undeclared:service:osv.dev");
    assert_eq!(
        osv.len(),
        1,
        "expected exactly 1 undeclared:service:osv.dev finding; got: {:?}",
        trust_budget_findings(&result)
    );
}

// ── 14. External-service scanner: skips target/ build output ────────

/// Bug-3 regression (defense): synthetic `target/debug/build/foo/output.rs`
/// containing a URL. Sensor MUST NOT emit a service finding for that
/// file — `target/` is build output, not real surface.
#[tokio::test]
async fn external_service_scanner_skips_target_dir() {
    let tmp = make_brain_root();
    let target_subdir = tmp.path()
        .join("target")
        .join("debug")
        .join("build")
        .join("foo");
    std::fs::create_dir_all(&target_subdir).expect("create target subdir");
    std::fs::write(
        target_subdir.join("output.rs"),
        "let url = \"https://target-build.example.com/v1\";\n",
    )
    .expect("write output.rs");

    let result = analyze_trust_budget(tmp.path().to_str().unwrap()).await;

    let target_findings = trust_budget_findings(&result)
        .into_iter()
        .filter(|f| {
            f["name"]
                .as_str()
                .map(|n| n.contains("target-build.example.com"))
                .unwrap_or(false)
        })
        .collect::<Vec<_>>();
    assert!(
        target_findings.is_empty(),
        "URL inside target/ MUST be skipped (build output, not real surface); got: {:?}",
        target_findings
    );
}

// ── 10. Recursion guard — Q7 hard rule ──────────────────────────────

/// The validator MUST be pure file-read + JSON-Schema-validate. NO
/// shell-out. NO `std::process::Command`. NO `Stdio`. NO `std::process`.
/// This test reads the source of `trust_budget.rs`, locates the
/// `analyze_trust_budget` and `analyze_trust_budget_path` function
/// spans, and grep-checks for forbidden patterns within the entire
/// file (since the trust-budget logic lives in helper functions called
/// from `analyze_trust_budget_path`, we apply the check to the whole
/// file — there's no other public entry point that could legally
/// shell out).
#[test]
fn recursion_guard_no_command_in_validator_span() {
    let path = locate_trust_budget_source();
    let source = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));

    // Validator's own surface (the file) — this includes
    // `analyze_trust_budget`, `analyze_trust_budget_path`, and all
    // their helper functions. The C3 design has all logic in this
    // single file (per the brief: "Single file (mirror
    // `capability_hygiene.rs` pattern)"); so the file-level scan IS
    // the validator-span scan.

    let forbidden = [
        "std::process::Command",
        "process::Command",
        "Command::new",
        "Stdio",
        "std::process",
        "duct::cmd",
        "subprocess::",
    ];
    for pat in forbidden.iter() {
        assert!(
            !source.contains(pat),
            "Q7 recursion-guard violated: `trust_budget.rs` contains forbidden \
             shell-execution pattern `{pat}`. The validator must be pure file-read + \
             JSON-Schema-validate. See E-B2-4 plan Q7."
        );
    }

    // Defense-in-depth: also reject patterns that suggest the
    // validator is donning a hat or invoking the Skill / Bash / Edit
    // / Write tool surface — same defensive posture as
    // `hat_contract_sensor_behavior.rs::recursion_guard_no_command_in_validator_span`.
    let suspicious = ["Skill::", "execute_skill", "invoke_tool"];
    for pat in suspicious.iter() {
        assert!(
            !source.contains(pat),
            "Q7 recursion-guard tripped on suspicious pattern `{pat}` inside \
             `trust_budget.rs`. The validator should not invoke tools or skills \
             — surface the violation to the operator instead."
        );
    }

    // Cargo.toml dependency check — assert no shell-execution crates
    // were added to neurogrim-sensory. The brief explicitly forbids
    // `walkdir`, `subprocess`, `duct`, `which`, `shell-words`.
    let cargo_toml_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml");
    let cargo_toml = std::fs::read_to_string(&cargo_toml_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", cargo_toml_path.display()));
    let forbidden_deps = [
        "\nwalkdir = ",
        "\nwhich = ",
        "\nsubprocess = ",
        "\nduct = ",
        "\nshell-words = ",
    ];
    for dep in forbidden_deps.iter() {
        assert!(
            !cargo_toml.contains(dep),
            "Q7 recursion-guard violated at dependency level: Cargo.toml grew \
             shell-execution / walker dependency `{}`. Trust-budget must not link \
             to shell-execution crates. See E-B2-4 plan Q7 + Q1.",
            dep.trim()
        );
    }
}
