//! `Cargo.lock` parsing via the RustSec-maintained `cargo-lock` crate.
//!
//! Extracts deduplicated `(name, version)` tuples for every package
//! sourced from `crates.io`. Workspace-local path deps, git deps,
//! and alternative registries are excluded — OSV coverage does not
//! extend to those sources, and our scoring model does not have a
//! sensible way to represent "we can't check this."

use anyhow::{Context, Result};
use cargo_lock::Lockfile;
use std::collections::BTreeSet;
use std::path::Path;

use crate::supply_chain_sca::Package;

/// Parse the `Cargo.lock` at `project_root/Cargo.lock` and return the
/// deduplicated set of packages sourced from `crates.io`.
///
/// # Errors
///
/// Returns an error if `Cargo.lock` is missing or malformed. Callers
/// should treat this as a "sensor cannot run" signal and emit an
/// appropriate CMDB finding rather than propagating the error to the
/// user — a failed scan is reported, not thrown.
pub fn parse(project_root: &Path) -> Result<Vec<Package>> {
    let lockfile_path = project_root.join("Cargo.lock");
    let lockfile = Lockfile::load(&lockfile_path)
        .with_context(|| format!("failed to load {}", lockfile_path.display()))?;

    let mut seen: BTreeSet<(String, String)> = BTreeSet::new();
    for pkg in &lockfile.packages {
        if !is_crates_io_source(&pkg.source) {
            continue;
        }
        seen.insert((pkg.name.as_str().to_owned(), pkg.version.to_string()));
    }

    Ok(seen
        .into_iter()
        .map(|(name, version)| Package::crates_io(name, version))
        .collect())
}

/// Check whether a package's source is the canonical `crates.io`
/// registry.
///
/// Packages with `None` source (workspace-local path deps), git
/// sources, local path sources, or non-crates.io alternative
/// registries all return `false`.
fn is_crates_io_source(source: &Option<cargo_lock::SourceId>) -> bool {
    match source {
        Some(src) => src.is_default_registry(),
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::TempDir;

    fn write_lockfile(dir: &Path, content: &str) {
        let path = dir.join("Cargo.lock");
        let mut f = std::fs::File::create(path).expect("create Cargo.lock");
        f.write_all(content.trim_start().as_bytes()).expect("write");
    }

    #[test]
    fn parses_simple_crates_io_package() {
        let tmp = TempDir::new().unwrap();
        write_lockfile(
            tmp.path(),
            r#"
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
"#,
        );
        let pkgs = parse(tmp.path()).unwrap();
        assert_eq!(pkgs.len(), 1, "expected 1 crates.io pkg, got {pkgs:?}");
        assert_eq!(pkgs[0].name, "serde");
        assert_eq!(pkgs[0].version, "1.0.228");
    }

    #[test]
    fn excludes_local_path_deps() {
        // A workspace-local dep has no `source` field in the lockfile.
        let tmp = TempDir::new().unwrap();
        write_lockfile(
            tmp.path(),
            r#"
version = 3

[[package]]
name = "my-local-crate"
version = "0.1.0"
"#,
        );
        let pkgs = parse(tmp.path()).unwrap();
        assert!(
            pkgs.is_empty(),
            "expected empty pkg list (local dep excluded), got {pkgs:?}"
        );
    }

    #[test]
    fn excludes_git_sources() {
        let tmp = TempDir::new().unwrap();
        write_lockfile(
            tmp.path(),
            r#"
version = 3

[[package]]
name = "some-git-crate"
version = "0.1.0"
source = "git+https://github.com/user/repo#abc123def456abc123def456abc123def456abc1"
"#,
        );
        let pkgs = parse(tmp.path()).unwrap();
        assert!(
            pkgs.is_empty(),
            "expected empty pkg list (git dep excluded), got {pkgs:?}"
        );
    }

    #[test]
    fn mixed_lockfile_keeps_only_crates_io() {
        let tmp = TempDir::new().unwrap();
        write_lockfile(
            tmp.path(),
            r#"
version = 3

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

[[package]]
name = "my-local-crate"
version = "0.1.0"

[[package]]
name = "some-git-crate"
version = "0.1.0"
source = "git+https://github.com/user/repo#abc123def456abc123def456abc123def456abc1"

[[package]]
name = "anyhow"
version = "1.0.102"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
"#,
        );
        let pkgs = parse(tmp.path()).unwrap();
        assert_eq!(pkgs.len(), 2, "expected 2 crates.io pkgs, got {pkgs:?}");
        assert!(pkgs.iter().any(|p| p.name == "serde"));
        assert!(pkgs.iter().any(|p| p.name == "anyhow"));
        assert!(!pkgs.iter().any(|p| p.name == "my-local-crate"));
        assert!(!pkgs.iter().any(|p| p.name == "some-git-crate"));
    }

    #[test]
    fn output_is_deterministic_and_deduped() {
        let tmp = TempDir::new().unwrap();
        write_lockfile(
            tmp.path(),
            r#"
version = 3

[[package]]
name = "zzz-last"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

[[package]]
name = "aaa-first"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
"#,
        );
        let pkgs = parse(tmp.path()).unwrap();
        // BTreeSet ordering: aaa-first, then zzz-last.
        assert_eq!(pkgs.len(), 2);
        assert_eq!(pkgs[0].name, "aaa-first");
        assert_eq!(pkgs[1].name, "zzz-last");
    }

    #[test]
    fn errors_when_lockfile_missing() {
        let tmp = TempDir::new().unwrap();
        let err = parse(tmp.path()).expect_err("expected error for missing Cargo.lock");
        let msg = format!("{err:#}");
        assert!(
            msg.contains("Cargo.lock"),
            "error should mention Cargo.lock; got: {msg}"
        );
    }

    #[test]
    fn parses_real_neurogrim_lockfile() {
        // Sanity check against the actual NeuroGrim workspace lockfile.
        // Locates it relative to this crate's manifest dir. Does not
        // assert exact counts (they drift with dep updates) but does
        // require non-zero + inclusion of a known dep.
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        let workspace_root = Path::new(manifest_dir)
            .parent()
            .expect("crate parent")
            .parent()
            .expect("workspace root");
        if !workspace_root.join("Cargo.lock").exists() {
            // Skip when run outside the workspace (tarballed tests etc.).
            return;
        }
        let pkgs = parse(workspace_root).expect("parse our own lockfile");
        assert!(!pkgs.is_empty(), "expected non-empty dep list");
        // `cargo-lock` is one of our direct deps; its presence proves
        // we're reading the right lockfile.
        assert!(
            pkgs.iter().any(|p| p.name == "cargo-lock"),
            "expected cargo-lock in our own dep graph; got names: {:?}",
            pkgs.iter().map(|p| &p.name).collect::<Vec<_>>()
        );
    }
}
