//! `yarn.lock` parser for the supply-chain-sca sensor.
//!
//! Yarn 1.x (Classic) and Yarn 2+ (Berry) both use a custom space-
//! indented text format that's hostile to hand-rolling cleanly.
//! We delegate to the `yarn-lock-parser` crate (nom-based;
//! handles both formats; ~170k DL on crates.io).
//!
//! # Filtering rules
//!
//! - **Git/file resolutions**: skip — no OSV coverage. yarn.lock
//!   stores `resolved: <url>`; we filter by URL prefix.
//! - **Workspace deps**: yarn workspaces share a root yarn.lock;
//!   the workspace packages themselves appear as entries with no
//!   `resolved` URL (they're symlinks). The empty-or-non-registry
//!   filter excludes them.
//! - **Aliased / patched deps**: yarn-lock-parser surfaces the
//!   resolved name; `entry.name` is what we query OSV for.
//!
//! # Trust surface
//!
//! `yarn-lock-parser` v0.10.x is the SMALLEST-ATTESTED external
//! crate in our SCA chain. Compensating mitigations:
//! - Pin to compatible-semver (`"0.10"`).
//! - Document explicitly in `audit/TOOL-TRUST-NOTES.md`.
//! - Limit blast radius: parser only consumes file content
//!   already present in the user's repo; it doesn't perform I/O,
//!   network, or process spawning.
//! - Output (`Vec<Entry>`) is read-only; we extract `(name,
//!   version)` and discard the rest. Defensive use posture.
//!
//! Hand-rolling Yarn 1.x is feasible if `yarn-lock-parser` is
//! ever flagged; estimated ~150-300 LOC. Berry is harder.

use anyhow::{Context, Result};
use std::collections::BTreeSet;
use std::path::Path;

use crate::supply_chain_sca::Package;

/// Parse `<project_root>/yarn.lock` and return deduplicated
/// npm-registry-sourced packages.
pub fn parse_yarn_lock(project_root: &Path) -> Result<Vec<Package>> {
    let path = project_root.join("yarn.lock");
    let raw = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    parse_yarn_lock_str(&raw)
}

fn parse_yarn_lock_str(raw: &str) -> Result<Vec<Package>> {
    let parsed = yarn_lock_parser::parse_str(raw)
        .map_err(|e| anyhow::anyhow!("yarn.lock parse: {e}"))?;

    let mut seen: BTreeSet<(String, String)> = BTreeSet::new();
    for entry in parsed.entries {
        if entry.name.is_empty() || entry.version.is_empty() {
            continue;
        }
        if !is_npm_registry_resolved(entry.resolved) {
            continue;
        }
        seen.insert((entry.name.to_string(), entry.version.to_string()));
    }

    Ok(seen
        .into_iter()
        .map(|(name, version)| Package::npm(name, version))
        .collect())
}

fn is_npm_registry_resolved(resolved: &str) -> bool {
    if resolved.is_empty() {
        // Empty resolved = workspace symlink; skip.
        return false;
    }
    // Yarn 1.x: `resolved "https://registry.npmjs.org/..."`.
    // Yarn Berry: `resolution: "lodash@npm:4.17.21"` doesn't carry
    // a URL but has the canonical npm: protocol marker. The crate
    // normalizes this via `entry.resolved` for v1 only; Berry
    // entries may have empty resolved + non-empty descriptors.
    // Conservative: only accept canonical-registry tarball URLs.
    resolved.starts_with("https://registry.npmjs.org/")
        || resolved.starts_with("https://registry.yarnpkg.com/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::TempDir;

    // Yarn 1.x (Classic) reference shape — what `yarn install`
    // produces today on a non-Berry project.
    const YARN_V1_FIXTURE: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz#a7e84e1c9d6a3e7fcd5f9c0c3b9e9b9c6e8c8c8c"
  integrity sha512-AAAAAAAAAAAAAAAAAAAAAAAAAA==

"@scope/pkg@^1.0.0":
  version "1.0.0"
  resolved "https://registry.npmjs.org/@scope/pkg/-/pkg-1.0.0.tgz#abc"
  integrity sha512-BBBBBBBBBBBBBBBBBBBBBBBBBB==

local-symlink@workspace:packages/local:
  version "0.0.0-use.local"
  resolved ""

from-git@^1.0.0:
  version "1.0.0"
  resolved "git+https://github.com/x/y.git#abc"
"#;

    #[test]
    fn yarn_v1_parses_canonical_registry_packages() {
        let pkgs = parse_yarn_lock_str(YARN_V1_FIXTURE).unwrap();
        let names: Vec<&str> = pkgs.iter().map(|p| p.name.as_str()).collect();
        assert!(names.contains(&"lodash"), "got: {names:?}");
        assert!(names.contains(&"@scope/pkg"), "got: {names:?}");
        // Ecosystem tag.
        for pkg in &pkgs {
            assert_eq!(pkg.ecosystem, "npm");
        }
    }

    #[test]
    fn yarn_v1_excludes_workspace_symlink() {
        let pkgs = parse_yarn_lock_str(YARN_V1_FIXTURE).unwrap();
        assert!(!pkgs.iter().any(|p| p.name == "local-symlink"));
    }

    #[test]
    fn yarn_v1_excludes_git_resolution() {
        let pkgs = parse_yarn_lock_str(YARN_V1_FIXTURE).unwrap();
        assert!(!pkgs.iter().any(|p| p.name == "from-git"));
    }

    #[test]
    fn yarn_v1_dedups_repeated_versions() {
        let raw = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz#a"
  integrity sha512-X==

lodash@^4.0.0:
  version "4.17.21"
  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz#a"
  integrity sha512-X==
"#;
        let pkgs = parse_yarn_lock_str(raw).unwrap();
        // Two version-spec lines but same resolved (name, version) →
        // dedup to one.
        assert_eq!(pkgs.iter().filter(|p| p.name == "lodash").count(), 1);
    }

    #[test]
    fn yarn_v1_accepts_yarnpkg_com_mirror() {
        // yarnpkg.com used to be a mirror of npmjs.org during
        // Yarn 1.x's heyday; some lockfiles still reference it.
        let raw = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#a"
  integrity sha512-X==
"#;
        let pkgs = parse_yarn_lock_str(raw).unwrap();
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].name, "lodash");
    }

    #[test]
    fn yarn_v1_excludes_alt_registry() {
        let raw = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


internal@^1.0.0:
  version "1.0.0"
  resolved "https://internal.example.com/internal/1.0.0.tgz"
  integrity sha512-Y==
"#;
        let pkgs = parse_yarn_lock_str(raw).unwrap();
        assert!(pkgs.is_empty());
    }

    #[test]
    fn yarn_v1_round_trip_from_file() {
        let tmp = TempDir::new().unwrap();
        let mut f = std::fs::File::create(tmp.path().join("yarn.lock")).unwrap();
        f.write_all(YARN_V1_FIXTURE.as_bytes()).unwrap();
        let pkgs = parse_yarn_lock(tmp.path()).unwrap();
        assert!(pkgs.iter().any(|p| p.name == "lodash"));
    }

    #[test]
    fn malformed_yarn_lock_returns_error() {
        let raw = "this is not yarn.lock content";
        let res = parse_yarn_lock_str(raw);
        // The crate may either error or return zero entries
        // depending on its parsing strategy. Either is acceptable;
        // the SCA sensor's parent gracefully degrades. We assert
        // the function does NOT panic.
        match res {
            Ok(pkgs) => assert!(pkgs.is_empty()),
            Err(_) => {} // also OK
        }
    }
}
